const eightLevels = [
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 8],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 9],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 10],
    },
    {
      id: 3,
      highlight: false,
      colour: "blue",
      numbers: [2, 4, 11],
    },
    {
      id: 4,
      highlight: false,
      colour: "blue",
      numbers: [3, 5, 12],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [4, 6, 13],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [5, 7, 14],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [6, 15],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [0, 9, 16],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [1, 8, 10, 17],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [2, 9, 11, 18],
    },
    {
      id: 11,
      highlight: true,
      colour: "blue",
      numbers: [3, 10, 12, 19],
    },
    {
      id: 12,
      highlight: true,
      colour: "blue",
      numbers: [4, 11, 13, 20],
    },
    {
      id: 13,
      highlight: true,
      colour: "yellow",
      numbers: [5, 12, 14, 21],
    },
    {
      id: 14,
      highlight: true,
      colour: "yellow",
      numbers: [6, 13, 15, 22],
    },
    {
      id: 15,
      highlight: true,
      colour: "yellow",
      numbers: [7, 14, 23],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [8, 17, 24],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [9, 16, 18, 25],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [10, 17, 19, 26],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [11, 18, 20, 27],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [12, 19, 21, 28],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [13, 20, 22, 29],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [14, 21, 23, 30],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [15, 22, 31],
    },
    {
      id: 24,
      highlight: false,
      colour: "blue",
      numbers: [16, 25, 32],
    },
    {
      id: 25,
      highlight: true,
      colour: "blue",
      numbers: [17, 24, 26, 33],
    },
    {
      id: 26,
      highlight: true,
      colour: "blue",
      numbers: [18, 25, 27, 34],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [19, 26, 28, 35],
    },
    {
      id: 28,
      highlight: true,
      colour: "blue",
      numbers: [20, 27, 29, 36],
    },
    {
      id: 29,
      highlight: true,
      colour: "blue",
      numbers: [21, 28, 30, 37],
    },
    {
      id: 30,
      highlight: true,
      colour: "blue",
      numbers: [22, 29, 31, 38],
    },
    {
      id: 31,
      highlight: false,
      colour: "blue",
      numbers: [23, 30, 39],
    },
    {
      id: 32,
      highlight: false,
      colour: "blue",
      numbers: [24, 33, 40],
    },
    {
      id: 33,
      highlight: true,
      colour: "blue",
      numbers: [25, 32, 34, 41],
    },
    {
      id: 34,
      highlight: true,
      colour: "blue",
      numbers: [26, 33, 35, 42],
    },
    {
      id: 35,
      highlight: true,
      colour: "blue",
      numbers: [27, 34, 36, 43],
    },
    {
      id: 36,
      highlight: true,
      colour: "blue",
      numbers: [28, 35, 37, 44],
    },
    {
      id: 37,
      highlight: true,
      colour: "blue",
      numbers: [29, 36, 38, 45],
    },
    {
      id: 38,
      highlight: true,
      colour: "blue",
      numbers: [30, 37, 39, 46],
    },
    {
      id: 39,
      highlight: false,
      colour: "blue",
      numbers: [31, 38, 47],
    },
    {
      id: 40,
      highlight: true,
      colour: "blue",
      numbers: [32, 41, 48],
    },
    {
      id: 41,
      highlight: true,
      colour: "yellow",
      numbers: [33, 40, 42, 49],
    },
    {
      id: 42,
      highlight: false,
      colour: "yellow",
      numbers: [34, 41, 43, 50],
    },
    {
      id: 43,
      highlight: true,
      colour: "blue",
      numbers: [35, 42, 44, 51],
    },
    {
      id: 44,
      highlight: true,
      colour: "blue",
      numbers: [36, 43, 45, 52],
    },
    {
      id: 45,
      highlight: false,
      colour: "yellow",
      numbers: [37, 44, 46, 53],
    },
    {
      id: 46,
      highlight: true,
      colour: "yellow",
      numbers: [38, 45, 47, 54],
    },
    {
      id: 47,
      highlight: true,
      colour: "blue",
      numbers: [39, 46, 55],
    },
    {
      id: 48,
      highlight: true,
      colour: "yellow",
      numbers: [40, 49, 56],
    },
    {
      id: 49,
      highlight: true,
      colour: "yellow",
      numbers: [41, 48, 50, 57],
    },
    {
      id: 50,
      highlight: true,
      colour: "yellow",
      numbers: [42, 49, 51, 58],
    },
    {
      id: 51,
      highlight: true,
      colour: "blue",
      numbers: [43, 50, 52, 59],
    },
    {
      id: 52,
      highlight: true,
      colour: "blue",
      numbers: [44, 51, 53, 60],
    },
    {
      id: 53,
      highlight: true,
      colour: "yellow",
      numbers: [45, 52, 54, 61],
    },
    {
      id: 54,
      highlight: true,
      colour: "yellow",
      numbers: [46, 53, 55, 62],
    },
    {
      id: 55,
      highlight: true,
      colour: "yellow",
      numbers: [47, 54, 63],
    },
    {
      id: 56,
      highlight: false,
      colour: "yellow",
      numbers: [48, 57],
    },
    {
      id: 57,
      highlight: true,
      colour: "yellow",
      numbers: [49, 56, 58],
    },
    {
      id: 58,
      highlight: true,
      colour: "blue",
      numbers: [50, 57, 59],
    },
    {
      id: 59,
      highlight: false,
      colour: "blue",
      numbers: [51, 58, 60],
    },
    {
      id: 60,
      highlight: false,
      colour: "blue",
      numbers: [52, 59, 61],
    },
    {
      id: 61,
      highlight: true,
      colour: "blue",
      numbers: [53, 60, 62],
    },
    {
      id: 62,
      highlight: true,
      colour: "yellow",
      numbers: [54, 61, 63],
    },
    {
      id: 63,
      highlight: false,
      colour: "yellow",
      numbers: [55, 62],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 8],
    },
    {
      id: 1,
      highlight: true,
      colour: "blue",
      numbers: [0, 2, 9],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 10],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 11],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 12],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 13],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [5, 7, 14],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [6, 15],
    },
    {
      id: 8,
      highlight: true,
      colour: "blue",
      numbers: [0, 9, 16],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [1, 8, 10, 17],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [2, 9, 11, 18],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [3, 10, 12, 19],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [4, 11, 13, 20],
    },
    {
      id: 13,
      highlight: true,
      colour: "yellow",
      numbers: [5, 12, 14, 21],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [6, 13, 15, 22],
    },
    {
      id: 15,
      highlight: true,
      colour: "blue",
      numbers: [7, 14, 23],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [8, 17, 24],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [9, 16, 18, 25],
    },
    {
      id: 18,
      highlight: true,
      colour: "yellow",
      numbers: [10, 17, 19, 26],
    },
    {
      id: 19,
      highlight: false,
      colour: "blue",
      numbers: [11, 18, 20, 27],
    },
    {
      id: 20,
      highlight: false,
      colour: "blue",
      numbers: [12, 19, 21, 28],
    },
    {
      id: 21,
      highlight: true,
      colour: "yellow",
      numbers: [13, 20, 22, 29],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [14, 21, 23, 30],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [15, 22, 31],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [16, 25, 32],
    },
    {
      id: 25,
      highlight: false,
      colour: "yellow",
      numbers: [17, 24, 26, 33],
    },
    {
      id: 26,
      highlight: false,
      colour: "blue",
      numbers: [18, 25, 27, 34],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [19, 26, 28, 35],
    },
    {
      id: 28,
      highlight: true,
      colour: "blue",
      numbers: [20, 27, 29, 36],
    },
    {
      id: 29,
      highlight: false,
      colour: "blue",
      numbers: [21, 28, 30, 37],
    },
    {
      id: 30,
      highlight: false,
      colour: "yellow",
      numbers: [22, 29, 31, 38],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [23, 30, 39],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [24, 33, 40],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [25, 32, 34, 41],
    },
    {
      id: 34,
      highlight: false,
      colour: "blue",
      numbers: [26, 33, 35, 42],
    },
    {
      id: 35,
      highlight: true,
      colour: "blue",
      numbers: [27, 34, 36, 43],
    },
    {
      id: 36,
      highlight: true,
      colour: "blue",
      numbers: [28, 35, 37, 44],
    },
    {
      id: 37,
      highlight: false,
      colour: "blue",
      numbers: [29, 36, 38, 45],
    },
    {
      id: 38,
      highlight: false,
      colour: "yellow",
      numbers: [30, 37, 39, 46],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [31, 38, 47],
    },
    {
      id: 40,
      highlight: false,
      colour: "yellow",
      numbers: [32, 41, 48],
    },
    {
      id: 41,
      highlight: true,
      colour: "yellow",
      numbers: [33, 40, 42, 49],
    },
    {
      id: 42,
      highlight: true,
      colour: "yellow",
      numbers: [34, 41, 43, 50],
    },
    {
      id: 43,
      highlight: false,
      colour: "blue",
      numbers: [35, 42, 44, 51],
    },
    {
      id: 44,
      highlight: false,
      colour: "blue",
      numbers: [36, 43, 45, 52],
    },
    {
      id: 45,
      highlight: true,
      colour: "yellow",
      numbers: [37, 44, 46, 53],
    },
    {
      id: 46,
      highlight: true,
      colour: "yellow",
      numbers: [38, 45, 47, 54],
    },
    {
      id: 47,
      highlight: false,
      colour: "yellow",
      numbers: [39, 46, 55],
    },
    {
      id: 48,
      highlight: true,
      colour: "blue",
      numbers: [40, 49, 56],
    },
    {
      id: 49,
      highlight: false,
      colour: "yellow",
      numbers: [41, 48, 50, 57],
    },
    {
      id: 50,
      highlight: true,
      colour: "yellow",
      numbers: [42, 49, 51, 58],
    },
    {
      id: 51,
      highlight: false,
      colour: "yellow",
      numbers: [43, 50, 52, 59],
    },
    {
      id: 52,
      highlight: false,
      colour: "yellow",
      numbers: [44, 51, 53, 60],
    },
    {
      id: 53,
      highlight: true,
      colour: "yellow",
      numbers: [45, 52, 54, 61],
    },
    {
      id: 54,
      highlight: false,
      colour: "yellow",
      numbers: [46, 53, 55, 62],
    },
    {
      id: 55,
      highlight: true,
      colour: "blue",
      numbers: [47, 54, 63],
    },
    {
      id: 56,
      highlight: true,
      colour: "blue",
      numbers: [48, 57],
    },
    {
      id: 57,
      highlight: true,
      colour: "blue",
      numbers: [49, 56, 58],
    },
    {
      id: 58,
      highlight: false,
      colour: "yellow",
      numbers: [50, 57, 59],
    },
    {
      id: 59,
      highlight: false,
      colour: "yellow",
      numbers: [51, 58, 60],
    },
    {
      id: 60,
      highlight: false,
      colour: "yellow",
      numbers: [52, 59, 61],
    },
    {
      id: 61,
      highlight: false,
      colour: "yellow",
      numbers: [53, 60, 62],
    },
    {
      id: 62,
      highlight: true,
      colour: "blue",
      numbers: [54, 61, 63],
    },
    {
      id: 63,
      highlight: true,
      colour: "blue",
      numbers: [55, 62],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 8],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 9],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 10],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 11],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 12],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [4, 6, 13],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [5, 7, 14],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [6, 15],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [0, 9, 16],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [1, 8, 10, 17],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [2, 9, 11, 18],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [3, 10, 12, 19],
    },
    {
      id: 12,
      highlight: true,
      colour: "blue",
      numbers: [4, 11, 13, 20],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [5, 12, 14, 21],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [6, 13, 15, 22],
    },
    {
      id: 15,
      highlight: true,
      colour: "blue",
      numbers: [7, 14, 23],
    },
    {
      id: 16,
      highlight: true,
      colour: "yellow",
      numbers: [8, 17, 24],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [9, 16, 18, 25],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [10, 17, 19, 26],
    },
    {
      id: 19,
      highlight: false,
      colour: "blue",
      numbers: [11, 18, 20, 27],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [12, 19, 21, 28],
    },
    {
      id: 21,
      highlight: false,
      colour: "blue",
      numbers: [13, 20, 22, 29],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [14, 21, 23, 30],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [15, 22, 31],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [16, 25, 32],
    },
    {
      id: 25,
      highlight: false,
      colour: "yellow",
      numbers: [17, 24, 26, 33],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [18, 25, 27, 34],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [19, 26, 28, 35],
    },
    {
      id: 28,
      highlight: false,
      colour: "blue",
      numbers: [20, 27, 29, 36],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [21, 28, 30, 37],
    },
    {
      id: 30,
      highlight: false,
      colour: "blue",
      numbers: [22, 29, 31, 38],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [23, 30, 39],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [24, 33, 40],
    },
    {
      id: 33,
      highlight: false,
      colour: "blue",
      numbers: [25, 32, 34, 41],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [26, 33, 35, 42],
    },
    {
      id: 35,
      highlight: false,
      colour: "blue",
      numbers: [27, 34, 36, 43],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [28, 35, 37, 44],
    },
    {
      id: 37,
      highlight: false,
      colour: "yellow",
      numbers: [29, 36, 38, 45],
    },
    {
      id: 38,
      highlight: false,
      colour: "yellow",
      numbers: [30, 37, 39, 46],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [31, 38, 47],
    },
    {
      id: 40,
      highlight: true,
      colour: "blue",
      numbers: [32, 41, 48],
    },
    {
      id: 41,
      highlight: true,
      colour: "blue",
      numbers: [33, 40, 42, 49],
    },
    {
      id: 42,
      highlight: false,
      colour: "blue",
      numbers: [34, 41, 43, 50],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [35, 42, 44, 51],
    },
    {
      id: 44,
      highlight: false,
      colour: "blue",
      numbers: [36, 43, 45, 52],
    },
    {
      id: 45,
      highlight: false,
      colour: "yellow",
      numbers: [37, 44, 46, 53],
    },
    {
      id: 46,
      highlight: true,
      colour: "yellow",
      numbers: [38, 45, 47, 54],
    },
    {
      id: 47,
      highlight: true,
      colour: "yellow",
      numbers: [39, 46, 55],
    },
    {
      id: 48,
      highlight: true,
      colour: "blue",
      numbers: [40, 49, 56],
    },
    {
      id: 49,
      highlight: true,
      colour: "blue",
      numbers: [41, 48, 50, 57],
    },
    {
      id: 50,
      highlight: true,
      colour: "blue",
      numbers: [42, 49, 51, 58],
    },
    {
      id: 51,
      highlight: true,
      colour: "blue",
      numbers: [43, 50, 52, 59],
    },
    {
      id: 52,
      highlight: true,
      colour: "yellow",
      numbers: [44, 51, 53, 60],
    },
    {
      id: 53,
      highlight: true,
      colour: "yellow",
      numbers: [45, 52, 54, 61],
    },
    {
      id: 54,
      highlight: true,
      colour: "yellow",
      numbers: [46, 53, 55, 62],
    },
    {
      id: 55,
      highlight: true,
      colour: "yellow",
      numbers: [47, 54, 63],
    },
    {
      id: 56,
      highlight: false,
      colour: "yellow",
      numbers: [48, 57],
    },
    {
      id: 57,
      highlight: true,
      colour: "blue",
      numbers: [49, 56, 58],
    },
    {
      id: 58,
      highlight: true,
      colour: "blue",
      numbers: [50, 57, 59],
    },
    {
      id: 59,
      highlight: false,
      colour: "yellow",
      numbers: [51, 58, 60],
    },
    {
      id: 60,
      highlight: false,
      colour: "yellow",
      numbers: [52, 59, 61],
    },
    {
      id: 61,
      highlight: true,
      colour: "yellow",
      numbers: [53, 60, 62],
    },
    {
      id: 62,
      highlight: true,
      colour: "yellow",
      numbers: [54, 61, 63],
    },
    {
      id: 63,
      highlight: false,
      colour: "yellow",
      numbers: [55, 62],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 8],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 9],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 10],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 11],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 12],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 13],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [5, 7, 14],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [6, 15],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [0, 9, 16],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [1, 8, 10, 17],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [2, 9, 11, 18],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [3, 10, 12, 19],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [4, 11, 13, 20],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [5, 12, 14, 21],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [6, 13, 15, 22],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [7, 14, 23],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [8, 17, 24],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [9, 16, 18, 25],
    },
    {
      id: 18,
      highlight: false,
      colour: "blue",
      numbers: [10, 17, 19, 26],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [11, 18, 20, 27],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [12, 19, 21, 28],
    },
    {
      id: 21,
      highlight: false,
      colour: "blue",
      numbers: [13, 20, 22, 29],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [14, 21, 23, 30],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [15, 22, 31],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [16, 25, 32],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [17, 24, 26, 33],
    },
    {
      id: 26,
      highlight: false,
      colour: "blue",
      numbers: [18, 25, 27, 34],
    },
    {
      id: 27,
      highlight: true,
      colour: "yellow",
      numbers: [19, 26, 28, 35],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [20, 27, 29, 36],
    },
    {
      id: 29,
      highlight: false,
      colour: "blue",
      numbers: [21, 28, 30, 37],
    },
    {
      id: 30,
      highlight: true,
      colour: "yellow",
      numbers: [22, 29, 31, 38],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [23, 30, 39],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [24, 33, 40],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [25, 32, 34, 41],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [26, 33, 35, 42],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [27, 34, 36, 43],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [28, 35, 37, 44],
    },
    {
      id: 37,
      highlight: false,
      colour: "yellow",
      numbers: [29, 36, 38, 45],
    },
    {
      id: 38,
      highlight: false,
      colour: "yellow",
      numbers: [30, 37, 39, 46],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [31, 38, 47],
    },
    {
      id: 40,
      highlight: false,
      colour: "yellow",
      numbers: [32, 41, 48],
    },
    {
      id: 41,
      highlight: true,
      colour: "blue",
      numbers: [33, 40, 42, 49],
    },
    {
      id: 42,
      highlight: true,
      colour: "blue",
      numbers: [34, 41, 43, 50],
    },
    {
      id: 43,
      highlight: false,
      colour: "blue",
      numbers: [35, 42, 44, 51],
    },
    {
      id: 44,
      highlight: false,
      colour: "blue",
      numbers: [36, 43, 45, 52],
    },
    {
      id: 45,
      highlight: true,
      colour: "blue",
      numbers: [37, 44, 46, 53],
    },
    {
      id: 46,
      highlight: true,
      colour: "blue",
      numbers: [38, 45, 47, 54],
    },
    {
      id: 47,
      highlight: false,
      colour: "yellow",
      numbers: [39, 46, 55],
    },
    {
      id: 48,
      highlight: false,
      colour: "yellow",
      numbers: [40, 49, 56],
    },
    {
      id: 49,
      highlight: false,
      colour: "yellow",
      numbers: [41, 48, 50, 57],
    },
    {
      id: 50,
      highlight: false,
      colour: "blue",
      numbers: [42, 49, 51, 58],
    },
    {
      id: 51,
      highlight: true,
      colour: "yellow",
      numbers: [43, 50, 52, 59],
    },
    {
      id: 52,
      highlight: true,
      colour: "yellow",
      numbers: [44, 51, 53, 60],
    },
    {
      id: 53,
      highlight: false,
      colour: "blue",
      numbers: [45, 52, 54, 61],
    },
    {
      id: 54,
      highlight: false,
      colour: "yellow",
      numbers: [46, 53, 55, 62],
    },
    {
      id: 55,
      highlight: false,
      colour: "yellow",
      numbers: [47, 54, 63],
    },
    {
      id: 56,
      highlight: false,
      colour: "yellow",
      numbers: [48, 57],
    },
    {
      id: 57,
      highlight: false,
      colour: "yellow",
      numbers: [49, 56, 58],
    },
    {
      id: 58,
      highlight: true,
      colour: "yellow",
      numbers: [50, 57, 59],
    },
    {
      id: 59,
      highlight: true,
      colour: "yellow",
      numbers: [51, 58, 60],
    },
    {
      id: 60,
      highlight: true,
      colour: "yellow",
      numbers: [52, 59, 61],
    },
    {
      id: 61,
      highlight: true,
      colour: "yellow",
      numbers: [53, 60, 62],
    },
    {
      id: 62,
      highlight: false,
      colour: "yellow",
      numbers: [54, 61, 63],
    },
    {
      id: 63,
      highlight: false,
      colour: "yellow",
      numbers: [55, 62],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 8],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 9],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 10],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 11],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 12],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 13],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [5, 7, 14],
    },
    {
      id: 7,
      highlight: false,
      colour: "blue",
      numbers: [6, 15],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [0, 9, 16],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [1, 8, 10, 17],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [2, 9, 11, 18],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [3, 10, 12, 19],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [4, 11, 13, 20],
    },
    {
      id: 13,
      highlight: true,
      colour: "yellow",
      numbers: [5, 12, 14, 21],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [6, 13, 15, 22],
    },
    {
      id: 15,
      highlight: false,
      colour: "blue",
      numbers: [7, 14, 23],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [8, 17, 24],
    },
    {
      id: 17,
      highlight: false,
      colour: "yellow",
      numbers: [9, 16, 18, 25],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [10, 17, 19, 26],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [11, 18, 20, 27],
    },
    {
      id: 20,
      highlight: true,
      colour: "yellow",
      numbers: [12, 19, 21, 28],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [13, 20, 22, 29],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [14, 21, 23, 30],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [15, 22, 31],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [16, 25, 32],
    },
    {
      id: 25,
      highlight: false,
      colour: "yellow",
      numbers: [17, 24, 26, 33],
    },
    {
      id: 26,
      highlight: false,
      colour: "blue",
      numbers: [18, 25, 27, 34],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [19, 26, 28, 35],
    },
    {
      id: 28,
      highlight: true,
      colour: "blue",
      numbers: [20, 27, 29, 36],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [21, 28, 30, 37],
    },
    {
      id: 30,
      highlight: true,
      colour: "yellow",
      numbers: [22, 29, 31, 38],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [23, 30, 39],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [24, 33, 40],
    },
    {
      id: 33,
      highlight: true,
      colour: "yellow",
      numbers: [25, 32, 34, 41],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [26, 33, 35, 42],
    },
    {
      id: 35,
      highlight: true,
      colour: "blue",
      numbers: [27, 34, 36, 43],
    },
    {
      id: 36,
      highlight: true,
      colour: "blue",
      numbers: [28, 35, 37, 44],
    },
    {
      id: 37,
      highlight: false,
      colour: "blue",
      numbers: [29, 36, 38, 45],
    },
    {
      id: 38,
      highlight: false,
      colour: "yellow",
      numbers: [30, 37, 39, 46],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [31, 38, 47],
    },
    {
      id: 40,
      highlight: true,
      colour: "blue",
      numbers: [32, 41, 48],
    },
    {
      id: 41,
      highlight: true,
      colour: "yellow",
      numbers: [33, 40, 42, 49],
    },
    {
      id: 42,
      highlight: false,
      colour: "yellow",
      numbers: [34, 41, 43, 50],
    },
    {
      id: 43,
      highlight: true,
      colour: "yellow",
      numbers: [35, 42, 44, 51],
    },
    {
      id: 44,
      highlight: true,
      colour: "blue",
      numbers: [36, 43, 45, 52],
    },
    {
      id: 45,
      highlight: false,
      colour: "yellow",
      numbers: [37, 44, 46, 53],
    },
    {
      id: 46,
      highlight: false,
      colour: "yellow",
      numbers: [38, 45, 47, 54],
    },
    {
      id: 47,
      highlight: false,
      colour: "yellow",
      numbers: [39, 46, 55],
    },
    {
      id: 48,
      highlight: false,
      colour: "blue",
      numbers: [40, 49, 56],
    },
    {
      id: 49,
      highlight: true,
      colour: "blue",
      numbers: [41, 48, 50, 57],
    },
    {
      id: 50,
      highlight: true,
      colour: "yellow",
      numbers: [42, 49, 51, 58],
    },
    {
      id: 51,
      highlight: false,
      colour: "yellow",
      numbers: [43, 50, 52, 59],
    },
    {
      id: 52,
      highlight: false,
      colour: "yellow",
      numbers: [44, 51, 53, 60],
    },
    {
      id: 53,
      highlight: false,
      colour: "yellow",
      numbers: [45, 52, 54, 61],
    },
    {
      id: 54,
      highlight: false,
      colour: "yellow",
      numbers: [46, 53, 55, 62],
    },
    {
      id: 55,
      highlight: false,
      colour: "yellow",
      numbers: [47, 54, 63],
    },
    {
      id: 56,
      highlight: false,
      colour: "blue",
      numbers: [48, 57],
    },
    {
      id: 57,
      highlight: true,
      colour: "blue",
      numbers: [49, 56, 58],
    },
    {
      id: 58,
      highlight: false,
      colour: "yellow",
      numbers: [50, 57, 59],
    },
    {
      id: 59,
      highlight: false,
      colour: "yellow",
      numbers: [51, 58, 60],
    },
    {
      id: 60,
      highlight: false,
      colour: "yellow",
      numbers: [52, 59, 61],
    },
    {
      id: 61,
      highlight: false,
      colour: "yellow",
      numbers: [53, 60, 62],
    },
    {
      id: 62,
      highlight: false,
      colour: "yellow",
      numbers: [54, 61, 63],
    },
    {
      id: 63,
      highlight: false,
      colour: "yellow",
      numbers: [55, 62],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 8],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 9],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 10],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 11],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 12],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [4, 6, 13],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [5, 7, 14],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [6, 15],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [0, 9, 16],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [1, 8, 10, 17],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [2, 9, 11, 18],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [3, 10, 12, 19],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [4, 11, 13, 20],
    },
    {
      id: 13,
      highlight: true,
      colour: "yellow",
      numbers: [5, 12, 14, 21],
    },
    {
      id: 14,
      highlight: true,
      colour: "yellow",
      numbers: [6, 13, 15, 22],
    },
    {
      id: 15,
      highlight: true,
      colour: "yellow",
      numbers: [7, 14, 23],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [8, 17, 24],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [9, 16, 18, 25],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [10, 17, 19, 26],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [11, 18, 20, 27],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [12, 19, 21, 28],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [13, 20, 22, 29],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [14, 21, 23, 30],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [15, 22, 31],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [16, 25, 32],
    },
    {
      id: 25,
      highlight: false,
      colour: "yellow",
      numbers: [17, 24, 26, 33],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [18, 25, 27, 34],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [19, 26, 28, 35],
    },
    {
      id: 28,
      highlight: false,
      colour: "yellow",
      numbers: [20, 27, 29, 36],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [21, 28, 30, 37],
    },
    {
      id: 30,
      highlight: false,
      colour: "yellow",
      numbers: [22, 29, 31, 38],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [23, 30, 39],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [24, 33, 40],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [25, 32, 34, 41],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [26, 33, 35, 42],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [27, 34, 36, 43],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [28, 35, 37, 44],
    },
    {
      id: 37,
      highlight: false,
      colour: "yellow",
      numbers: [29, 36, 38, 45],
    },
    {
      id: 38,
      highlight: false,
      colour: "yellow",
      numbers: [30, 37, 39, 46],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [31, 38, 47],
    },
    {
      id: 40,
      highlight: true,
      colour: "blue",
      numbers: [32, 41, 48],
    },
    {
      id: 41,
      highlight: true,
      colour: "yellow",
      numbers: [33, 40, 42, 49],
    },
    {
      id: 42,
      highlight: false,
      colour: "yellow",
      numbers: [34, 41, 43, 50],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [35, 42, 44, 51],
    },
    {
      id: 44,
      highlight: false,
      colour: "yellow",
      numbers: [36, 43, 45, 52],
    },
    {
      id: 45,
      highlight: false,
      colour: "yellow",
      numbers: [37, 44, 46, 53],
    },
    {
      id: 46,
      highlight: true,
      colour: "yellow",
      numbers: [38, 45, 47, 54],
    },
    {
      id: 47,
      highlight: true,
      colour: "blue",
      numbers: [39, 46, 55],
    },
    {
      id: 48,
      highlight: true,
      colour: "yellow",
      numbers: [40, 49, 56],
    },
    {
      id: 49,
      highlight: true,
      colour: "yellow",
      numbers: [41, 48, 50, 57],
    },
    {
      id: 50,
      highlight: true,
      colour: "yellow",
      numbers: [42, 49, 51, 58],
    },
    {
      id: 51,
      highlight: false,
      colour: "yellow",
      numbers: [43, 50, 52, 59],
    },
    {
      id: 52,
      highlight: false,
      colour: "yellow",
      numbers: [44, 51, 53, 60],
    },
    {
      id: 53,
      highlight: true,
      colour: "yellow",
      numbers: [45, 52, 54, 61],
    },
    {
      id: 54,
      highlight: true,
      colour: "yellow",
      numbers: [46, 53, 55, 62],
    },
    {
      id: 55,
      highlight: true,
      colour: "yellow",
      numbers: [47, 54, 63],
    },
    {
      id: 56,
      highlight: true,
      colour: "blue",
      numbers: [48, 57],
    },
    {
      id: 57,
      highlight: true,
      colour: "yellow",
      numbers: [49, 56, 58],
    },
    {
      id: 58,
      highlight: true,
      colour: "blue",
      numbers: [50, 57, 59],
    },
    {
      id: 59,
      highlight: false,
      colour: "yellow",
      numbers: [51, 58, 60],
    },
    {
      id: 60,
      highlight: false,
      colour: "yellow",
      numbers: [52, 59, 61],
    },
    {
      id: 61,
      highlight: true,
      colour: "blue",
      numbers: [53, 60, 62],
    },
    {
      id: 62,
      highlight: true,
      colour: "yellow",
      numbers: [54, 61, 63],
    },
    {
      id: 63,
      highlight: true,
      colour: "blue",
      numbers: [55, 62],
    },
  ],
];

export default eightLevels;
