const fiveLevels = [
  [
    {
      id: 0,
      highlight: true,
      colour: "yellow",
      numbers: [1, 5],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 6],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 7],
    },
    {
      id: 3,
      highlight: true,
      colour: "yellow",
      numbers: [2, 4, 8],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [3, 9],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [0, 6, 10],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [1, 5, 7, 11],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [2, 6, 8, 12],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [3, 7, 9, 13],
    },
    {
      id: 9,
      highlight: true,
      colour: "blue",
      numbers: [4, 8, 14],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [5, 11, 15],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [6, 10, 12, 16],
    },
    {
      id: 12,
      highlight: false,
      colour: "blue",
      numbers: [7, 11, 13, 17],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [8, 12, 14, 18],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [9, 13, 19],
    },
    {
      id: 15,
      highlight: true,
      colour: "yellow",
      numbers: [10, 16, 20],
    },
    {
      id: 16,
      highlight: false,
      colour: "blue",
      numbers: [11, 15, 17, 21],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [12, 16, 18, 22],
    },
    {
      id: 18,
      highlight: false,
      colour: "blue",
      numbers: [13, 17, 19, 23],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [14, 18, 24],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [15, 21],
    },
    {
      id: 21,
      highlight: true,
      colour: "blue",
      numbers: [16, 20, 22],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [17, 21, 23],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [18, 22, 24],
    },
    {
      id: 24,
      highlight: true,
      colour: "blue",
      numbers: [19, 23],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "yellow",
      numbers: [1, 5],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 6],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 7],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 8],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [3, 9],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [0, 6, 10],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [1, 5, 7, 11],
    },
    {
      id: 7,
      highlight: false,
      colour: "blue",
      numbers: [2, 6, 8, 12],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [3, 7, 9, 13],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [4, 8, 14],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [5, 11, 15],
    },
    {
      id: 11,
      highlight: true,
      colour: "blue",
      numbers: [6, 10, 12, 16],
    },
    {
      id: 12,
      highlight: true,
      colour: "blue",
      numbers: [7, 11, 13, 17],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [8, 12, 14, 18],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [9, 13, 19],
    },
    {
      id: 15,
      highlight: true,
      colour: "yellow",
      numbers: [10, 16, 20],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [11, 15, 17, 21],
    },
    {
      id: 17,
      highlight: false,
      colour: "blue",
      numbers: [12, 16, 18, 22],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [13, 17, 19, 23],
    },
    {
      id: 19,
      highlight: true,
      colour: "yellow",
      numbers: [14, 18, 24],
    },
    {
      id: 20,
      highlight: true,
      colour: "yellow",
      numbers: [15, 21],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [16, 20, 22],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [17, 21, 23],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [18, 22, 24],
    },
    {
      id: 24,
      highlight: true,
      colour: "yellow",
      numbers: [19, 23],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 5],
    },
    {
      id: 1,
      highlight: true,
      colour: "blue",
      numbers: [0, 2, 6],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 7],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 8],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 9],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [0, 6, 10],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [1, 5, 7, 11],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [2, 6, 8, 12],
    },
    {
      id: 8,
      highlight: true,
      colour: "blue",
      numbers: [3, 7, 9, 13],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [4, 8, 14],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [5, 11, 15],
    },
    {
      id: 11,
      highlight: true,
      colour: "blue",
      numbers: [6, 10, 12, 16],
    },
    {
      id: 12,
      highlight: false,
      colour: "blue",
      numbers: [7, 11, 13, 17],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [8, 12, 14, 18],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [9, 13, 19],
    },
    {
      id: 15,
      highlight: true,
      colour: "yellow",
      numbers: [10, 16, 20],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [11, 15, 17, 21],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [12, 16, 18, 22],
    },
    {
      id: 18,
      highlight: true,
      colour: "blue",
      numbers: [13, 17, 19, 23],
    },
    {
      id: 19,
      highlight: true,
      colour: "yellow",
      numbers: [14, 18, 24],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [15, 21],
    },
    {
      id: 21,
      highlight: true,
      colour: "blue",
      numbers: [16, 20, 22],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [17, 21, 23],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [18, 22, 24],
    },
    {
      id: 24,
      highlight: true,
      colour: "blue",
      numbers: [19, 23],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 5],
    },
    {
      id: 1,
      highlight: false,
      colour: "blue",
      numbers: [0, 2, 6],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 7],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 8],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [3, 9],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [0, 6, 10],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [1, 5, 7, 11],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [2, 6, 8, 12],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [3, 7, 9, 13],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [4, 8, 14],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [5, 11, 15],
    },
    {
      id: 11,
      highlight: false,
      colour: "blue",
      numbers: [6, 10, 12, 16],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [7, 11, 13, 17],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [8, 12, 14, 18],
    },
    {
      id: 14,
      highlight: true,
      colour: "yellow",
      numbers: [9, 13, 19],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [10, 16, 20],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [11, 15, 17, 21],
    },
    {
      id: 17,
      highlight: false,
      colour: "yellow",
      numbers: [12, 16, 18, 22],
    },
    {
      id: 18,
      highlight: true,
      colour: "yellow",
      numbers: [13, 17, 19, 23],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [14, 18, 24],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [15, 21],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [16, 20, 22],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [17, 21, 23],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [18, 22, 24],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [19, 23],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 5],
    },
    {
      id: 1,
      highlight: true,
      colour: "blue",
      numbers: [0, 2, 6],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 7],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 8],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 9],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [0, 6, 10],
    },
    {
      id: 6,
      highlight: false,
      colour: "blue",
      numbers: [1, 5, 7, 11],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [2, 6, 8, 12],
    },
    {
      id: 8,
      highlight: false,
      colour: "blue",
      numbers: [3, 7, 9, 13],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [4, 8, 14],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [5, 11, 15],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [6, 10, 12, 16],
    },
    {
      id: 12,
      highlight: true,
      colour: "blue",
      numbers: [7, 11, 13, 17],
    },
    {
      id: 13,
      highlight: true,
      colour: "yellow",
      numbers: [8, 12, 14, 18],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [9, 13, 19],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [10, 16, 20],
    },
    {
      id: 16,
      highlight: false,
      colour: "blue",
      numbers: [11, 15, 17, 21],
    },
    {
      id: 17,
      highlight: false,
      colour: "yellow",
      numbers: [12, 16, 18, 22],
    },
    {
      id: 18,
      highlight: false,
      colour: "blue",
      numbers: [13, 17, 19, 23],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [14, 18, 24],
    },
    {
      id: 20,
      highlight: true,
      colour: "yellow",
      numbers: [15, 21],
    },
    {
      id: 21,
      highlight: true,
      colour: "yellow",
      numbers: [16, 20, 22],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [17, 21, 23],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [18, 22, 24],
    },
    {
      id: 24,
      highlight: true,
      colour: "yellow",
      numbers: [19, 23],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 5],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 6],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 7],
    },
    {
      id: 3,
      highlight: true,
      colour: "yellow",
      numbers: [2, 4, 8],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 9],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [0, 6, 10],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [1, 5, 7, 11],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [2, 6, 8, 12],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [3, 7, 9, 13],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [4, 8, 14],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [5, 11, 15],
    },
    {
      id: 11,
      highlight: true,
      colour: "blue",
      numbers: [6, 10, 12, 16],
    },
    {
      id: 12,
      highlight: true,
      colour: "blue",
      numbers: [7, 11, 13, 17],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [8, 12, 14, 18],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [9, 13, 19],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [10, 16, 20],
    },
    {
      id: 16,
      highlight: true,
      colour: "yellow",
      numbers: [11, 15, 17, 21],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [12, 16, 18, 22],
    },
    {
      id: 18,
      highlight: true,
      colour: "yellow",
      numbers: [13, 17, 19, 23],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [14, 18, 24],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [15, 21],
    },
    {
      id: 21,
      highlight: true,
      colour: "yellow",
      numbers: [16, 20, 22],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [17, 21, 23],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [18, 22, 24],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [19, 23],
    },
  ],
];

export default fiveLevels;
