const fourLevels = [
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 4],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 5],
    },
    {
      id: 2,
      highlight: false,
      colour: "blue",
      numbers: [1, 3, 6],
    },
    {
      id: 3,
      highlight: false,
      colour: "blue",
      numbers: [2, 7],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [0, 5, 8],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [1, 4, 6, 9],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [2, 5, 7, 10],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [3, 6, 11],
    },
    {
      id: 8,
      highlight: true,
      colour: "blue",
      numbers: [4, 9, 12],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [5, 8, 10, 13],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [6, 9, 11, 14],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [7, 10, 15],
    },
    {
      id: 12,
      highlight: false,
      colour: "blue",
      numbers: [8, 13],
    },
    {
      id: 13,
      highlight: false,
      colour: "blue",
      numbers: [9, 12, 14],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [10, 13, 15],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [11, 14],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 4],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 5],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 6],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 7],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [0, 5, 8],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [1, 4, 6, 9],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [2, 5, 7, 10],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [3, 6, 11],
    },
    {
      id: 8,
      highlight: false,
      colour: "blue",
      numbers: [4, 9, 12],
    },
    {
      id: 9,
      highlight: false,
      colour: "blue",
      numbers: [5, 8, 10, 13],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [6, 9, 11, 14],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [7, 10, 15],
    },
    {
      id: 12,
      highlight: false,
      colour: "blue",
      numbers: [8, 13],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [9, 12, 14],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [10, 13, 15],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [11, 14],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 4],
    },
    {
      id: 1,
      highlight: false,
      colour: "blue",
      numbers: [0, 2, 5],
    },
    {
      id: 2,
      highlight: false,
      colour: "blue",
      numbers: [1, 3, 6],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 7],
    },
    {
      id: 4,
      highlight: false,
      colour: "blue",
      numbers: [0, 5, 8],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [1, 4, 6, 9],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [2, 5, 7, 10],
    },
    {
      id: 7,
      highlight: false,
      colour: "blue",
      numbers: [3, 6, 11],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [4, 9, 12],
    },
    {
      id: 9,
      highlight: true,
      colour: "blue",
      numbers: [5, 8, 10, 13],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [6, 9, 11, 14],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [7, 10, 15],
    },
    {
      id: 12,
      highlight: true,
      colour: "yellow",
      numbers: [8, 13],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [9, 12, 14],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [10, 13, 15],
    },
    {
      id: 15,
      highlight: true,
      colour: "yellow",
      numbers: [11, 14],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 4],
    },
    {
      id: 1,
      highlight: true,
      colour: "blue",
      numbers: [0, 2, 5],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 6],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 7],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [0, 5, 8],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [1, 4, 6, 9],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [2, 5, 7, 10],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [3, 6, 11],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [4, 9, 12],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [5, 8, 10, 13],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [6, 9, 11, 14],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [7, 10, 15],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [8, 13],
    },
    {
      id: 13,
      highlight: true,
      colour: "yellow",
      numbers: [9, 12, 14],
    },
    {
      id: 14,
      highlight: true,
      colour: "yellow",
      numbers: [10, 13, 15],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [11, 14],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 4],
    },
    {
      id: 1,
      highlight: false,
      colour: "blue",
      numbers: [0, 2, 5],
    },
    {
      id: 2,
      highlight: false,
      colour: "blue",
      numbers: [1, 3, 6],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 7],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [0, 5, 8],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [1, 4, 6, 9],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [2, 5, 7, 10],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [3, 6, 11],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [4, 9, 12],
    },
    {
      id: 9,
      highlight: true,
      colour: "blue",
      numbers: [5, 8, 10, 13],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [6, 9, 11, 14],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [7, 10, 15],
    },
    {
      id: 12,
      highlight: true,
      colour: "blue",
      numbers: [8, 13],
    },
    {
      id: 13,
      highlight: false,
      colour: "blue",
      numbers: [9, 12, 14],
    },
    {
      id: 14,
      highlight: false,
      colour: "blue",
      numbers: [10, 13, 15],
    },
    {
      id: 15,
      highlight: true,
      colour: "blue",
      numbers: [11, 14],
    },
  ],
];

export default fourLevels;
