const nineLevels = [
  [
    {
      id: 0,
      highlight: true,
      colour: "yellow",
      numbers: [1, 9],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 10],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 11],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 12],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 13],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 14],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [5, 7, 15],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [6, 8, 16],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [7, 17],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [0, 10, 18],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [1, 9, 11, 19],
    },
    {
      id: 11,
      highlight: false,
      colour: "blue",
      numbers: [2, 10, 12, 20],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [3, 11, 13, 21],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [4, 12, 14, 22],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [5, 13, 15, 23],
    },
    {
      id: 15,
      highlight: false,
      colour: "blue",
      numbers: [6, 14, 16, 24],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [7, 15, 17, 25],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [8, 16, 26],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [9, 19, 27],
    },
    {
      id: 19,
      highlight: false,
      colour: "blue",
      numbers: [10, 18, 20, 28],
    },
    {
      id: 20,
      highlight: false,
      colour: "blue",
      numbers: [11, 19, 21, 29],
    },
    {
      id: 21,
      highlight: true,
      colour: "blue",
      numbers: [12, 20, 22, 30],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [13, 21, 23, 31],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [14, 22, 24, 32],
    },
    {
      id: 24,
      highlight: false,
      colour: "blue",
      numbers: [15, 23, 25, 33],
    },
    {
      id: 25,
      highlight: false,
      colour: "blue",
      numbers: [16, 24, 26, 34],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [17, 25, 35],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [18, 28, 36],
    },
    {
      id: 28,
      highlight: true,
      colour: "blue",
      numbers: [19, 27, 29, 37],
    },
    {
      id: 29,
      highlight: false,
      colour: "blue",
      numbers: [20, 28, 30, 38],
    },
    {
      id: 30,
      highlight: true,
      colour: "blue",
      numbers: [21, 29, 31, 39],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [22, 30, 32, 40],
    },
    {
      id: 32,
      highlight: true,
      colour: "blue",
      numbers: [23, 31, 33, 41],
    },
    {
      id: 33,
      highlight: false,
      colour: "blue",
      numbers: [24, 32, 34, 42],
    },
    {
      id: 34,
      highlight: true,
      colour: "blue",
      numbers: [25, 33, 35, 43],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [26, 34, 44],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [27, 37, 45],
    },
    {
      id: 37,
      highlight: false,
      colour: "yellow",
      numbers: [28, 36, 38, 46],
    },
    {
      id: 38,
      highlight: false,
      colour: "blue",
      numbers: [29, 37, 39, 47],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [30, 38, 40, 48],
    },
    {
      id: 40,
      highlight: false,
      colour: "yellow",
      numbers: [31, 39, 41, 49],
    },
    {
      id: 41,
      highlight: false,
      colour: "yellow",
      numbers: [32, 40, 42, 50],
    },
    {
      id: 42,
      highlight: false,
      colour: "blue",
      numbers: [33, 41, 43, 51],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [34, 42, 44, 52],
    },
    {
      id: 44,
      highlight: false,
      colour: "yellow",
      numbers: [35, 43, 53],
    },
    {
      id: 45,
      highlight: false,
      colour: "yellow",
      numbers: [36, 46, 54],
    },
    {
      id: 46,
      highlight: true,
      colour: "blue",
      numbers: [37, 45, 47, 55],
    },
    {
      id: 47,
      highlight: false,
      colour: "blue",
      numbers: [38, 46, 48, 56],
    },
    {
      id: 48,
      highlight: true,
      colour: "blue",
      numbers: [39, 47, 49, 57],
    },
    {
      id: 49,
      highlight: false,
      colour: "yellow",
      numbers: [40, 48, 50, 58],
    },
    {
      id: 50,
      highlight: true,
      colour: "blue",
      numbers: [41, 49, 51, 59],
    },
    {
      id: 51,
      highlight: false,
      colour: "blue",
      numbers: [42, 50, 52, 60],
    },
    {
      id: 52,
      highlight: true,
      colour: "blue",
      numbers: [43, 51, 53, 61],
    },
    {
      id: 53,
      highlight: false,
      colour: "yellow",
      numbers: [44, 52, 62],
    },
    {
      id: 54,
      highlight: false,
      colour: "yellow",
      numbers: [45, 55, 63],
    },
    {
      id: 55,
      highlight: false,
      colour: "blue",
      numbers: [46, 54, 56, 64],
    },
    {
      id: 56,
      highlight: false,
      colour: "blue",
      numbers: [47, 55, 57, 65],
    },
    {
      id: 57,
      highlight: true,
      colour: "blue",
      numbers: [48, 56, 58, 66],
    },
    {
      id: 58,
      highlight: false,
      colour: "yellow",
      numbers: [49, 57, 59, 67],
    },
    {
      id: 59,
      highlight: true,
      colour: "blue",
      numbers: [50, 58, 60, 68],
    },
    {
      id: 60,
      highlight: false,
      colour: "blue",
      numbers: [51, 59, 61, 69],
    },
    {
      id: 61,
      highlight: false,
      colour: "blue",
      numbers: [52, 60, 62, 70],
    },
    {
      id: 62,
      highlight: false,
      colour: "yellow",
      numbers: [53, 61, 71],
    },
    {
      id: 63,
      highlight: true,
      colour: "yellow",
      numbers: [54, 64, 72],
    },
    {
      id: 64,
      highlight: false,
      colour: "yellow",
      numbers: [55, 63, 65, 73],
    },
    {
      id: 65,
      highlight: false,
      colour: "blue",
      numbers: [56, 64, 66, 74],
    },
    {
      id: 66,
      highlight: false,
      colour: "yellow",
      numbers: [57, 65, 67, 75],
    },
    {
      id: 67,
      highlight: false,
      colour: "yellow",
      numbers: [58, 66, 68, 76],
    },
    {
      id: 68,
      highlight: false,
      colour: "yellow",
      numbers: [59, 67, 69, 77],
    },
    {
      id: 69,
      highlight: false,
      colour: "blue",
      numbers: [60, 68, 70, 78],
    },
    {
      id: 70,
      highlight: false,
      colour: "yellow",
      numbers: [61, 69, 71, 79],
    },
    {
      id: 71,
      highlight: true,
      colour: "yellow",
      numbers: [62, 70, 80],
    },
    {
      id: 72,
      highlight: true,
      colour: "yellow",
      numbers: [63, 73],
    },
    {
      id: 73,
      highlight: false,
      colour: "yellow",
      numbers: [64, 72, 74],
    },
    {
      id: 74,
      highlight: true,
      colour: "yellow",
      numbers: [65, 73, 75],
    },
    {
      id: 75,
      highlight: false,
      colour: "yellow",
      numbers: [66, 74, 76],
    },
    {
      id: 76,
      highlight: false,
      colour: "yellow",
      numbers: [67, 75, 77],
    },
    {
      id: 77,
      highlight: false,
      colour: "yellow",
      numbers: [68, 76, 78],
    },
    {
      id: 78,
      highlight: true,
      colour: "yellow",
      numbers: [69, 77, 79],
    },
    {
      id: 79,
      highlight: false,
      colour: "yellow",
      numbers: [70, 78, 80],
    },
    {
      id: 80,
      highlight: true,
      colour: "yellow",
      numbers: [71, 79],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 9],
    },
    {
      id: 1,
      highlight: false,
      colour: "blue",
      numbers: [0, 2, 10],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 11],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 12],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 13],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [4, 6, 14],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [5, 7, 15],
    },
    {
      id: 7,
      highlight: false,
      colour: "blue",
      numbers: [6, 8, 16],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [7, 17],
    },
    {
      id: 9,
      highlight: false,
      colour: "blue",
      numbers: [0, 10, 18],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [1, 9, 11, 19],
    },
    {
      id: 11,
      highlight: false,
      colour: "blue",
      numbers: [2, 10, 12, 20],
    },
    {
      id: 12,
      highlight: true,
      colour: "yellow",
      numbers: [3, 11, 13, 21],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [4, 12, 14, 22],
    },
    {
      id: 14,
      highlight: true,
      colour: "yellow",
      numbers: [5, 13, 15, 23],
    },
    {
      id: 15,
      highlight: false,
      colour: "blue",
      numbers: [6, 14, 16, 24],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [7, 15, 17, 25],
    },
    {
      id: 17,
      highlight: false,
      colour: "blue",
      numbers: [8, 16, 26],
    },
    {
      id: 18,
      highlight: true,
      colour: "blue",
      numbers: [9, 19, 27],
    },
    {
      id: 19,
      highlight: false,
      colour: "blue",
      numbers: [10, 18, 20, 28],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [11, 19, 21, 29],
    },
    {
      id: 21,
      highlight: true,
      colour: "yellow",
      numbers: [12, 20, 22, 30],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [13, 21, 23, 31],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [14, 22, 24, 32],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [15, 23, 25, 33],
    },
    {
      id: 25,
      highlight: false,
      colour: "blue",
      numbers: [16, 24, 26, 34],
    },
    {
      id: 26,
      highlight: true,
      colour: "blue",
      numbers: [17, 25, 35],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [18, 28, 36],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [19, 27, 29, 37],
    },
    {
      id: 29,
      highlight: true,
      colour: "yellow",
      numbers: [20, 28, 30, 38],
    },
    {
      id: 30,
      highlight: false,
      colour: "yellow",
      numbers: [21, 29, 31, 39],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [22, 30, 32, 40],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [23, 31, 33, 41],
    },
    {
      id: 33,
      highlight: true,
      colour: "yellow",
      numbers: [24, 32, 34, 42],
    },
    {
      id: 34,
      highlight: true,
      colour: "yellow",
      numbers: [25, 33, 35, 43],
    },
    {
      id: 35,
      highlight: true,
      colour: "blue",
      numbers: [26, 34, 44],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [27, 37, 45],
    },
    {
      id: 37,
      highlight: false,
      colour: "yellow",
      numbers: [28, 36, 38, 46],
    },
    {
      id: 38,
      highlight: false,
      colour: "yellow",
      numbers: [29, 37, 39, 47],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [30, 38, 40, 48],
    },
    {
      id: 40,
      highlight: false,
      colour: "yellow",
      numbers: [31, 39, 41, 49],
    },
    {
      id: 41,
      highlight: false,
      colour: "yellow",
      numbers: [32, 40, 42, 50],
    },
    {
      id: 42,
      highlight: false,
      colour: "yellow",
      numbers: [33, 41, 43, 51],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [34, 42, 44, 52],
    },
    {
      id: 44,
      highlight: false,
      colour: "yellow",
      numbers: [35, 43, 53],
    },
    {
      id: 45,
      highlight: true,
      colour: "blue",
      numbers: [36, 46, 54],
    },
    {
      id: 46,
      highlight: true,
      colour: "yellow",
      numbers: [37, 45, 47, 55],
    },
    {
      id: 47,
      highlight: true,
      colour: "yellow",
      numbers: [38, 46, 48, 56],
    },
    {
      id: 48,
      highlight: false,
      colour: "yellow",
      numbers: [39, 47, 49, 57],
    },
    {
      id: 49,
      highlight: false,
      colour: "yellow",
      numbers: [40, 48, 50, 58],
    },
    {
      id: 50,
      highlight: false,
      colour: "yellow",
      numbers: [41, 49, 51, 59],
    },
    {
      id: 51,
      highlight: true,
      colour: "yellow",
      numbers: [42, 50, 52, 60],
    },
    {
      id: 52,
      highlight: true,
      colour: "yellow",
      numbers: [43, 51, 53, 61],
    },
    {
      id: 53,
      highlight: true,
      colour: "blue",
      numbers: [44, 52, 62],
    },
    {
      id: 54,
      highlight: true,
      colour: "blue",
      numbers: [45, 55, 63],
    },
    {
      id: 55,
      highlight: false,
      colour: "blue",
      numbers: [46, 54, 56, 64],
    },
    {
      id: 56,
      highlight: false,
      colour: "yellow",
      numbers: [47, 55, 57, 65],
    },
    {
      id: 57,
      highlight: true,
      colour: "yellow",
      numbers: [48, 56, 58, 66],
    },
    {
      id: 58,
      highlight: false,
      colour: "yellow",
      numbers: [49, 57, 59, 67],
    },
    {
      id: 59,
      highlight: true,
      colour: "yellow",
      numbers: [50, 58, 60, 68],
    },
    {
      id: 60,
      highlight: false,
      colour: "yellow",
      numbers: [51, 59, 61, 69],
    },
    {
      id: 61,
      highlight: false,
      colour: "blue",
      numbers: [52, 60, 62, 70],
    },
    {
      id: 62,
      highlight: true,
      colour: "blue",
      numbers: [53, 61, 71],
    },
    {
      id: 63,
      highlight: false,
      colour: "blue",
      numbers: [54, 64, 72],
    },
    {
      id: 64,
      highlight: true,
      colour: "blue",
      numbers: [55, 63, 65, 73],
    },
    {
      id: 65,
      highlight: false,
      colour: "blue",
      numbers: [56, 64, 66, 74],
    },
    {
      id: 66,
      highlight: true,
      colour: "yellow",
      numbers: [57, 65, 67, 75],
    },
    {
      id: 67,
      highlight: false,
      colour: "yellow",
      numbers: [58, 66, 68, 76],
    },
    {
      id: 68,
      highlight: true,
      colour: "yellow",
      numbers: [59, 67, 69, 77],
    },
    {
      id: 69,
      highlight: false,
      colour: "blue",
      numbers: [60, 68, 70, 78],
    },
    {
      id: 70,
      highlight: true,
      colour: "blue",
      numbers: [61, 69, 71, 79],
    },
    {
      id: 71,
      highlight: false,
      colour: "blue",
      numbers: [62, 70, 80],
    },
    {
      id: 72,
      highlight: false,
      colour: "yellow",
      numbers: [63, 73],
    },
    {
      id: 73,
      highlight: false,
      colour: "blue",
      numbers: [64, 72, 74],
    },
    {
      id: 74,
      highlight: true,
      colour: "blue",
      numbers: [65, 73, 75],
    },
    {
      id: 75,
      highlight: true,
      colour: "blue",
      numbers: [66, 74, 76],
    },
    {
      id: 76,
      highlight: false,
      colour: "yellow",
      numbers: [67, 75, 77],
    },
    {
      id: 77,
      highlight: true,
      colour: "blue",
      numbers: [68, 76, 78],
    },
    {
      id: 78,
      highlight: true,
      colour: "blue",
      numbers: [69, 77, 79],
    },
    {
      id: 79,
      highlight: false,
      colour: "blue",
      numbers: [70, 78, 80],
    },
    {
      id: 80,
      highlight: false,
      colour: "yellow",
      numbers: [71, 79],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 9],
    },
    {
      id: 1,
      highlight: false,
      colour: "blue",
      numbers: [0, 2, 10],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 11],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 12],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 13],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [4, 6, 14],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [5, 7, 15],
    },
    {
      id: 7,
      highlight: false,
      colour: "blue",
      numbers: [6, 8, 16],
    },
    {
      id: 8,
      highlight: true,
      colour: "blue",
      numbers: [7, 17],
    },
    {
      id: 9,
      highlight: false,
      colour: "blue",
      numbers: [0, 10, 18],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [1, 9, 11, 19],
    },
    {
      id: 11,
      highlight: true,
      colour: "blue",
      numbers: [2, 10, 12, 20],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [3, 11, 13, 21],
    },
    {
      id: 13,
      highlight: false,
      colour: "blue",
      numbers: [4, 12, 14, 22],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [5, 13, 15, 23],
    },
    {
      id: 15,
      highlight: true,
      colour: "blue",
      numbers: [6, 14, 16, 24],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [7, 15, 17, 25],
    },
    {
      id: 17,
      highlight: false,
      colour: "blue",
      numbers: [8, 16, 26],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [9, 19, 27],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [10, 18, 20, 28],
    },
    {
      id: 20,
      highlight: true,
      colour: "yellow",
      numbers: [11, 19, 21, 29],
    },
    {
      id: 21,
      highlight: true,
      colour: "yellow",
      numbers: [12, 20, 22, 30],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [13, 21, 23, 31],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [14, 22, 24, 32],
    },
    {
      id: 24,
      highlight: true,
      colour: "yellow",
      numbers: [15, 23, 25, 33],
    },
    {
      id: 25,
      highlight: true,
      colour: "blue",
      numbers: [16, 24, 26, 34],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [17, 25, 35],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [18, 28, 36],
    },
    {
      id: 28,
      highlight: false,
      colour: "yellow",
      numbers: [19, 27, 29, 37],
    },
    {
      id: 29,
      highlight: true,
      colour: "yellow",
      numbers: [20, 28, 30, 38],
    },
    {
      id: 30,
      highlight: false,
      colour: "yellow",
      numbers: [21, 29, 31, 39],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [22, 30, 32, 40],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [23, 31, 33, 41],
    },
    {
      id: 33,
      highlight: true,
      colour: "yellow",
      numbers: [24, 32, 34, 42],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [25, 33, 35, 43],
    },
    {
      id: 35,
      highlight: true,
      colour: "blue",
      numbers: [26, 34, 44],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [27, 37, 45],
    },
    {
      id: 37,
      highlight: false,
      colour: "blue",
      numbers: [28, 36, 38, 46],
    },
    {
      id: 38,
      highlight: false,
      colour: "yellow",
      numbers: [29, 37, 39, 47],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [30, 38, 40, 48],
    },
    {
      id: 40,
      highlight: false,
      colour: "yellow",
      numbers: [31, 39, 41, 49],
    },
    {
      id: 41,
      highlight: false,
      colour: "yellow",
      numbers: [32, 40, 42, 50],
    },
    {
      id: 42,
      highlight: false,
      colour: "yellow",
      numbers: [33, 41, 43, 51],
    },
    {
      id: 43,
      highlight: false,
      colour: "blue",
      numbers: [34, 42, 44, 52],
    },
    {
      id: 44,
      highlight: false,
      colour: "yellow",
      numbers: [35, 43, 53],
    },
    {
      id: 45,
      highlight: true,
      colour: "blue",
      numbers: [36, 46, 54],
    },
    {
      id: 46,
      highlight: false,
      colour: "yellow",
      numbers: [37, 45, 47, 55],
    },
    {
      id: 47,
      highlight: true,
      colour: "yellow",
      numbers: [38, 46, 48, 56],
    },
    {
      id: 48,
      highlight: false,
      colour: "yellow",
      numbers: [39, 47, 49, 57],
    },
    {
      id: 49,
      highlight: false,
      colour: "yellow",
      numbers: [40, 48, 50, 58],
    },
    {
      id: 50,
      highlight: false,
      colour: "yellow",
      numbers: [41, 49, 51, 59],
    },
    {
      id: 51,
      highlight: true,
      colour: "yellow",
      numbers: [42, 50, 52, 60],
    },
    {
      id: 52,
      highlight: false,
      colour: "yellow",
      numbers: [43, 51, 53, 61],
    },
    {
      id: 53,
      highlight: true,
      colour: "blue",
      numbers: [44, 52, 62],
    },
    {
      id: 54,
      highlight: false,
      colour: "yellow",
      numbers: [45, 55, 63],
    },
    {
      id: 55,
      highlight: true,
      colour: "blue",
      numbers: [46, 54, 56, 64],
    },
    {
      id: 56,
      highlight: true,
      colour: "yellow",
      numbers: [47, 55, 57, 65],
    },
    {
      id: 57,
      highlight: true,
      colour: "yellow",
      numbers: [48, 56, 58, 66],
    },
    {
      id: 58,
      highlight: false,
      colour: "yellow",
      numbers: [49, 57, 59, 67],
    },
    {
      id: 59,
      highlight: true,
      colour: "yellow",
      numbers: [50, 58, 60, 68],
    },
    {
      id: 60,
      highlight: true,
      colour: "yellow",
      numbers: [51, 59, 61, 69],
    },
    {
      id: 61,
      highlight: true,
      colour: "blue",
      numbers: [52, 60, 62, 70],
    },
    {
      id: 62,
      highlight: false,
      colour: "yellow",
      numbers: [53, 61, 71],
    },
    {
      id: 63,
      highlight: false,
      colour: "blue",
      numbers: [54, 64, 72],
    },
    {
      id: 64,
      highlight: true,
      colour: "blue",
      numbers: [55, 63, 65, 73],
    },
    {
      id: 65,
      highlight: true,
      colour: "blue",
      numbers: [56, 64, 66, 74],
    },
    {
      id: 66,
      highlight: false,
      colour: "yellow",
      numbers: [57, 65, 67, 75],
    },
    {
      id: 67,
      highlight: false,
      colour: "blue",
      numbers: [58, 66, 68, 76],
    },
    {
      id: 68,
      highlight: false,
      colour: "yellow",
      numbers: [59, 67, 69, 77],
    },
    {
      id: 69,
      highlight: true,
      colour: "blue",
      numbers: [60, 68, 70, 78],
    },
    {
      id: 70,
      highlight: true,
      colour: "blue",
      numbers: [61, 69, 71, 79],
    },
    {
      id: 71,
      highlight: false,
      colour: "blue",
      numbers: [62, 70, 80],
    },
    {
      id: 72,
      highlight: true,
      colour: "blue",
      numbers: [63, 73],
    },
    {
      id: 73,
      highlight: false,
      colour: "blue",
      numbers: [64, 72, 74],
    },
    {
      id: 74,
      highlight: false,
      colour: "yellow",
      numbers: [65, 73, 75],
    },
    {
      id: 75,
      highlight: true,
      colour: "blue",
      numbers: [66, 74, 76],
    },
    {
      id: 76,
      highlight: false,
      colour: "yellow",
      numbers: [67, 75, 77],
    },
    {
      id: 77,
      highlight: true,
      colour: "blue",
      numbers: [68, 76, 78],
    },
    {
      id: 78,
      highlight: false,
      colour: "yellow",
      numbers: [69, 77, 79],
    },
    {
      id: 79,
      highlight: false,
      colour: "blue",
      numbers: [70, 78, 80],
    },
    {
      id: 80,
      highlight: true,
      colour: "blue",
      numbers: [71, 79],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 9],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 10],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 11],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 12],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 13],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 14],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [5, 7, 15],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [6, 8, 16],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [7, 17],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [0, 10, 18],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [1, 9, 11, 19],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [2, 10, 12, 20],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [3, 11, 13, 21],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [4, 12, 14, 22],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [5, 13, 15, 23],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [6, 14, 16, 24],
    },
    {
      id: 16,
      highlight: true,
      colour: "yellow",
      numbers: [7, 15, 17, 25],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [8, 16, 26],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [9, 19, 27],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [10, 18, 20, 28],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [11, 19, 21, 29],
    },
    {
      id: 21,
      highlight: false,
      colour: "blue",
      numbers: [12, 20, 22, 30],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [13, 21, 23, 31],
    },
    {
      id: 23,
      highlight: false,
      colour: "blue",
      numbers: [14, 22, 24, 32],
    },
    {
      id: 24,
      highlight: true,
      colour: "blue",
      numbers: [15, 23, 25, 33],
    },
    {
      id: 25,
      highlight: false,
      colour: "yellow",
      numbers: [16, 24, 26, 34],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [17, 25, 35],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [18, 28, 36],
    },
    {
      id: 28,
      highlight: false,
      colour: "yellow",
      numbers: [19, 27, 29, 37],
    },
    {
      id: 29,
      highlight: false,
      colour: "blue",
      numbers: [20, 28, 30, 38],
    },
    {
      id: 30,
      highlight: true,
      colour: "blue",
      numbers: [21, 29, 31, 39],
    },
    {
      id: 31,
      highlight: true,
      colour: "blue",
      numbers: [22, 30, 32, 40],
    },
    {
      id: 32,
      highlight: true,
      colour: "blue",
      numbers: [23, 31, 33, 41],
    },
    {
      id: 33,
      highlight: false,
      colour: "blue",
      numbers: [24, 32, 34, 42],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [25, 33, 35, 43],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [26, 34, 44],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [27, 37, 45],
    },
    {
      id: 37,
      highlight: false,
      colour: "yellow",
      numbers: [28, 36, 38, 46],
    },
    {
      id: 38,
      highlight: true,
      colour: "blue",
      numbers: [29, 37, 39, 47],
    },
    {
      id: 39,
      highlight: true,
      colour: "blue",
      numbers: [30, 38, 40, 48],
    },
    {
      id: 40,
      highlight: false,
      colour: "blue",
      numbers: [31, 39, 41, 49],
    },
    {
      id: 41,
      highlight: true,
      colour: "blue",
      numbers: [32, 40, 42, 50],
    },
    {
      id: 42,
      highlight: true,
      colour: "blue",
      numbers: [33, 41, 43, 51],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [34, 42, 44, 52],
    },
    {
      id: 44,
      highlight: false,
      colour: "yellow",
      numbers: [35, 43, 53],
    },
    {
      id: 45,
      highlight: false,
      colour: "yellow",
      numbers: [36, 46, 54],
    },
    {
      id: 46,
      highlight: false,
      colour: "yellow",
      numbers: [37, 45, 47, 55],
    },
    {
      id: 47,
      highlight: false,
      colour: "blue",
      numbers: [38, 46, 48, 56],
    },
    {
      id: 48,
      highlight: true,
      colour: "blue",
      numbers: [39, 47, 49, 57],
    },
    {
      id: 49,
      highlight: true,
      colour: "blue",
      numbers: [40, 48, 50, 58],
    },
    {
      id: 50,
      highlight: true,
      colour: "blue",
      numbers: [41, 49, 51, 59],
    },
    {
      id: 51,
      highlight: false,
      colour: "blue",
      numbers: [42, 50, 52, 60],
    },
    {
      id: 52,
      highlight: false,
      colour: "yellow",
      numbers: [43, 51, 53, 61],
    },
    {
      id: 53,
      highlight: false,
      colour: "yellow",
      numbers: [44, 52, 62],
    },
    {
      id: 54,
      highlight: false,
      colour: "yellow",
      numbers: [45, 55, 63],
    },
    {
      id: 55,
      highlight: false,
      colour: "yellow",
      numbers: [46, 54, 56, 64],
    },
    {
      id: 56,
      highlight: true,
      colour: "blue",
      numbers: [47, 55, 57, 65],
    },
    {
      id: 57,
      highlight: false,
      colour: "blue",
      numbers: [48, 56, 58, 66],
    },
    {
      id: 58,
      highlight: true,
      colour: "blue",
      numbers: [49, 57, 59, 67],
    },
    {
      id: 59,
      highlight: false,
      colour: "blue",
      numbers: [50, 58, 60, 68],
    },
    {
      id: 60,
      highlight: true,
      colour: "blue",
      numbers: [51, 59, 61, 69],
    },
    {
      id: 61,
      highlight: false,
      colour: "yellow",
      numbers: [52, 60, 62, 70],
    },
    {
      id: 62,
      highlight: false,
      colour: "yellow",
      numbers: [53, 61, 71],
    },
    {
      id: 63,
      highlight: true,
      colour: "yellow",
      numbers: [54, 64, 72],
    },
    {
      id: 64,
      highlight: true,
      colour: "yellow",
      numbers: [55, 63, 65, 73],
    },
    {
      id: 65,
      highlight: false,
      colour: "yellow",
      numbers: [56, 64, 66, 74],
    },
    {
      id: 66,
      highlight: false,
      colour: "yellow",
      numbers: [57, 65, 67, 75],
    },
    {
      id: 67,
      highlight: false,
      colour: "yellow",
      numbers: [58, 66, 68, 76],
    },
    {
      id: 68,
      highlight: false,
      colour: "yellow",
      numbers: [59, 67, 69, 77],
    },
    {
      id: 69,
      highlight: false,
      colour: "yellow",
      numbers: [60, 68, 70, 78],
    },
    {
      id: 70,
      highlight: true,
      colour: "yellow",
      numbers: [61, 69, 71, 79],
    },
    {
      id: 71,
      highlight: true,
      colour: "yellow",
      numbers: [62, 70, 80],
    },
    {
      id: 72,
      highlight: false,
      colour: "yellow",
      numbers: [63, 73],
    },
    {
      id: 73,
      highlight: true,
      colour: "yellow",
      numbers: [64, 72, 74],
    },
    {
      id: 74,
      highlight: false,
      colour: "yellow",
      numbers: [65, 73, 75],
    },
    {
      id: 75,
      highlight: false,
      colour: "yellow",
      numbers: [66, 74, 76],
    },
    {
      id: 76,
      highlight: false,
      colour: "yellow",
      numbers: [67, 75, 77],
    },
    {
      id: 77,
      highlight: false,
      colour: "yellow",
      numbers: [68, 76, 78],
    },
    {
      id: 78,
      highlight: false,
      colour: "yellow",
      numbers: [69, 77, 79],
    },
    {
      id: 79,
      highlight: true,
      colour: "yellow",
      numbers: [70, 78, 80],
    },
    {
      id: 80,
      highlight: false,
      colour: "yellow",
      numbers: [71, 79],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 9],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 10],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 11],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 12],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 5, 13],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [4, 6, 14],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [5, 7, 15],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [6, 8, 16],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [7, 17],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [0, 10, 18],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [1, 9, 11, 19],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [2, 10, 12, 20],
    },
    {
      id: 12,
      highlight: true,
      colour: "yellow",
      numbers: [3, 11, 13, 21],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [4, 12, 14, 22],
    },
    {
      id: 14,
      highlight: true,
      colour: "yellow",
      numbers: [5, 13, 15, 23],
    },
    {
      id: 15,
      highlight: true,
      colour: "yellow",
      numbers: [6, 14, 16, 24],
    },
    {
      id: 16,
      highlight: true,
      colour: "yellow",
      numbers: [7, 15, 17, 25],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [8, 16, 26],
    },
    {
      id: 18,
      highlight: true,
      colour: "yellow",
      numbers: [9, 19, 27],
    },
    {
      id: 19,
      highlight: true,
      colour: "yellow",
      numbers: [10, 18, 20, 28],
    },
    {
      id: 20,
      highlight: true,
      colour: "yellow",
      numbers: [11, 19, 21, 29],
    },
    {
      id: 21,
      highlight: false,
      colour: "blue",
      numbers: [12, 20, 22, 30],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [13, 21, 23, 31],
    },
    {
      id: 23,
      highlight: false,
      colour: "blue",
      numbers: [14, 22, 24, 32],
    },
    {
      id: 24,
      highlight: true,
      colour: "yellow",
      numbers: [15, 23, 25, 33],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [16, 24, 26, 34],
    },
    {
      id: 26,
      highlight: true,
      colour: "yellow",
      numbers: [17, 25, 35],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [18, 28, 36],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [19, 27, 29, 37],
    },
    {
      id: 29,
      highlight: false,
      colour: "blue",
      numbers: [20, 28, 30, 38],
    },
    {
      id: 30,
      highlight: true,
      colour: "blue",
      numbers: [21, 29, 31, 39],
    },
    {
      id: 31,
      highlight: true,
      colour: "blue",
      numbers: [22, 30, 32, 40],
    },
    {
      id: 32,
      highlight: true,
      colour: "blue",
      numbers: [23, 31, 33, 41],
    },
    {
      id: 33,
      highlight: false,
      colour: "blue",
      numbers: [24, 32, 34, 42],
    },
    {
      id: 34,
      highlight: true,
      colour: "yellow",
      numbers: [25, 33, 35, 43],
    },
    {
      id: 35,
      highlight: true,
      colour: "blue",
      numbers: [26, 34, 44],
    },
    {
      id: 36,
      highlight: true,
      colour: "blue",
      numbers: [27, 37, 45],
    },
    {
      id: 37,
      highlight: true,
      colour: "blue",
      numbers: [28, 36, 38, 46],
    },
    {
      id: 38,
      highlight: true,
      colour: "blue",
      numbers: [29, 37, 39, 47],
    },
    {
      id: 39,
      highlight: true,
      colour: "blue",
      numbers: [30, 38, 40, 48],
    },
    {
      id: 40,
      highlight: false,
      colour: "blue",
      numbers: [31, 39, 41, 49],
    },
    {
      id: 41,
      highlight: true,
      colour: "blue",
      numbers: [32, 40, 42, 50],
    },
    {
      id: 42,
      highlight: true,
      colour: "blue",
      numbers: [33, 41, 43, 51],
    },
    {
      id: 43,
      highlight: true,
      colour: "blue",
      numbers: [34, 42, 44, 52],
    },
    {
      id: 44,
      highlight: true,
      colour: "blue",
      numbers: [35, 43, 53],
    },
    {
      id: 45,
      highlight: true,
      colour: "blue",
      numbers: [36, 46, 54],
    },
    {
      id: 46,
      highlight: true,
      colour: "yellow",
      numbers: [37, 45, 47, 55],
    },
    {
      id: 47,
      highlight: false,
      colour: "blue",
      numbers: [38, 46, 48, 56],
    },
    {
      id: 48,
      highlight: true,
      colour: "blue",
      numbers: [39, 47, 49, 57],
    },
    {
      id: 49,
      highlight: true,
      colour: "blue",
      numbers: [40, 48, 50, 58],
    },
    {
      id: 50,
      highlight: true,
      colour: "blue",
      numbers: [41, 49, 51, 59],
    },
    {
      id: 51,
      highlight: false,
      colour: "blue",
      numbers: [42, 50, 52, 60],
    },
    {
      id: 52,
      highlight: true,
      colour: "yellow",
      numbers: [43, 51, 53, 61],
    },
    {
      id: 53,
      highlight: true,
      colour: "blue",
      numbers: [44, 52, 62],
    },
    {
      id: 54,
      highlight: true,
      colour: "yellow",
      numbers: [45, 55, 63],
    },
    {
      id: 55,
      highlight: true,
      colour: "yellow",
      numbers: [46, 54, 56, 64],
    },
    {
      id: 56,
      highlight: true,
      colour: "yellow",
      numbers: [47, 55, 57, 65],
    },
    {
      id: 57,
      highlight: false,
      colour: "blue",
      numbers: [48, 56, 58, 66],
    },
    {
      id: 58,
      highlight: true,
      colour: "blue",
      numbers: [49, 57, 59, 67],
    },
    {
      id: 59,
      highlight: false,
      colour: "blue",
      numbers: [50, 58, 60, 68],
    },
    {
      id: 60,
      highlight: true,
      colour: "yellow",
      numbers: [51, 59, 61, 69],
    },
    {
      id: 61,
      highlight: true,
      colour: "yellow",
      numbers: [52, 60, 62, 70],
    },
    {
      id: 62,
      highlight: true,
      colour: "yellow",
      numbers: [53, 61, 71],
    },
    {
      id: 63,
      highlight: true,
      colour: "yellow",
      numbers: [54, 64, 72],
    },
    {
      id: 64,
      highlight: true,
      colour: "yellow",
      numbers: [55, 63, 65, 73],
    },
    {
      id: 65,
      highlight: true,
      colour: "yellow",
      numbers: [56, 64, 66, 74],
    },
    {
      id: 66,
      highlight: true,
      colour: "yellow",
      numbers: [57, 65, 67, 75],
    },
    {
      id: 67,
      highlight: true,
      colour: "blue",
      numbers: [58, 66, 68, 76],
    },
    {
      id: 68,
      highlight: true,
      colour: "yellow",
      numbers: [59, 67, 69, 77],
    },
    {
      id: 69,
      highlight: true,
      colour: "yellow",
      numbers: [60, 68, 70, 78],
    },
    {
      id: 70,
      highlight: true,
      colour: "yellow",
      numbers: [61, 69, 71, 79],
    },
    {
      id: 71,
      highlight: true,
      colour: "yellow",
      numbers: [62, 70, 80],
    },
    {
      id: 72,
      highlight: false,
      colour: "yellow",
      numbers: [63, 73],
    },
    {
      id: 73,
      highlight: true,
      colour: "yellow",
      numbers: [64, 72, 74],
    },
    {
      id: 74,
      highlight: true,
      colour: "yellow",
      numbers: [65, 73, 75],
    },
    {
      id: 75,
      highlight: true,
      colour: "blue",
      numbers: [66, 74, 76],
    },
    {
      id: 76,
      highlight: true,
      colour: "blue",
      numbers: [67, 75, 77],
    },
    {
      id: 77,
      highlight: true,
      colour: "blue",
      numbers: [68, 76, 78],
    },
    {
      id: 78,
      highlight: true,
      colour: "yellow",
      numbers: [69, 77, 79],
    },
    {
      id: 79,
      highlight: true,
      colour: "yellow",
      numbers: [70, 78, 80],
    },
    {
      id: 80,
      highlight: false,
      colour: "yellow",
      numbers: [71, 79],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 9],
    },
    {
      id: 1,
      highlight: true,
      colour: "blue",
      numbers: [0, 2, 10],
    },
    {
      id: 2,
      highlight: false,
      colour: "blue",
      numbers: [1, 3, 11],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 12],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 13],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 14],
    },
    {
      id: 6,
      highlight: false,
      colour: "blue",
      numbers: [5, 7, 15],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [6, 8, 16],
    },
    {
      id: 8,
      highlight: true,
      colour: "blue",
      numbers: [7, 17],
    },
    {
      id: 9,
      highlight: true,
      colour: "blue",
      numbers: [0, 10, 18],
    },
    {
      id: 10,
      highlight: false,
      colour: "blue",
      numbers: [1, 9, 11, 19],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [2, 10, 12, 20],
    },
    {
      id: 12,
      highlight: false,
      colour: "blue",
      numbers: [3, 11, 13, 21],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [4, 12, 14, 22],
    },
    {
      id: 14,
      highlight: false,
      colour: "blue",
      numbers: [5, 13, 15, 23],
    },
    {
      id: 15,
      highlight: true,
      colour: "yellow",
      numbers: [6, 14, 16, 24],
    },
    {
      id: 16,
      highlight: false,
      colour: "blue",
      numbers: [7, 15, 17, 25],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [8, 16, 26],
    },
    {
      id: 18,
      highlight: false,
      colour: "blue",
      numbers: [9, 19, 27],
    },
    {
      id: 19,
      highlight: true,
      colour: "yellow",
      numbers: [10, 18, 20, 28],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [11, 19, 21, 29],
    },
    {
      id: 21,
      highlight: true,
      colour: "blue",
      numbers: [12, 20, 22, 30],
    },
    {
      id: 22,
      highlight: false,
      colour: "blue",
      numbers: [13, 21, 23, 31],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [14, 22, 24, 32],
    },
    {
      id: 24,
      highlight: true,
      colour: "blue",
      numbers: [15, 23, 25, 33],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [16, 24, 26, 34],
    },
    {
      id: 26,
      highlight: false,
      colour: "blue",
      numbers: [17, 25, 35],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [18, 28, 36],
    },
    {
      id: 28,
      highlight: false,
      colour: "blue",
      numbers: [19, 27, 29, 37],
    },
    {
      id: 29,
      highlight: true,
      colour: "blue",
      numbers: [20, 28, 30, 38],
    },
    {
      id: 30,
      highlight: false,
      colour: "blue",
      numbers: [21, 29, 31, 39],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [22, 30, 32, 40],
    },
    {
      id: 32,
      highlight: false,
      colour: "blue",
      numbers: [23, 31, 33, 41],
    },
    {
      id: 33,
      highlight: true,
      colour: "blue",
      numbers: [24, 32, 34, 42],
    },
    {
      id: 34,
      highlight: false,
      colour: "blue",
      numbers: [25, 33, 35, 43],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [26, 34, 44],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [27, 37, 45],
    },
    {
      id: 37,
      highlight: false,
      colour: "yellow",
      numbers: [28, 36, 38, 46],
    },
    {
      id: 38,
      highlight: false,
      colour: "blue",
      numbers: [29, 37, 39, 47],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [30, 38, 40, 48],
    },
    {
      id: 40,
      highlight: false,
      colour: "yellow",
      numbers: [31, 39, 41, 49],
    },
    {
      id: 41,
      highlight: false,
      colour: "yellow",
      numbers: [32, 40, 42, 50],
    },
    {
      id: 42,
      highlight: false,
      colour: "blue",
      numbers: [33, 41, 43, 51],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [34, 42, 44, 52],
    },
    {
      id: 44,
      highlight: false,
      colour: "yellow",
      numbers: [35, 43, 53],
    },
    {
      id: 45,
      highlight: false,
      colour: "yellow",
      numbers: [36, 46, 54],
    },
    {
      id: 46,
      highlight: false,
      colour: "blue",
      numbers: [37, 45, 47, 55],
    },
    {
      id: 47,
      highlight: true,
      colour: "blue",
      numbers: [38, 46, 48, 56],
    },
    {
      id: 48,
      highlight: false,
      colour: "blue",
      numbers: [39, 47, 49, 57],
    },
    {
      id: 49,
      highlight: false,
      colour: "yellow",
      numbers: [40, 48, 50, 58],
    },
    {
      id: 50,
      highlight: false,
      colour: "blue",
      numbers: [41, 49, 51, 59],
    },
    {
      id: 51,
      highlight: true,
      colour: "blue",
      numbers: [42, 50, 52, 60],
    },
    {
      id: 52,
      highlight: false,
      colour: "blue",
      numbers: [43, 51, 53, 61],
    },
    {
      id: 53,
      highlight: false,
      colour: "yellow",
      numbers: [44, 52, 62],
    },
    {
      id: 54,
      highlight: false,
      colour: "blue",
      numbers: [45, 55, 63],
    },
    {
      id: 55,
      highlight: true,
      colour: "yellow",
      numbers: [46, 54, 56, 64],
    },
    {
      id: 56,
      highlight: true,
      colour: "blue",
      numbers: [47, 55, 57, 65],
    },
    {
      id: 57,
      highlight: true,
      colour: "blue",
      numbers: [48, 56, 58, 66],
    },
    {
      id: 58,
      highlight: false,
      colour: "blue",
      numbers: [49, 57, 59, 67],
    },
    {
      id: 59,
      highlight: true,
      colour: "blue",
      numbers: [50, 58, 60, 68],
    },
    {
      id: 60,
      highlight: true,
      colour: "blue",
      numbers: [51, 59, 61, 69],
    },
    {
      id: 61,
      highlight: true,
      colour: "yellow",
      numbers: [52, 60, 62, 70],
    },
    {
      id: 62,
      highlight: false,
      colour: "blue",
      numbers: [53, 61, 71],
    },
    {
      id: 63,
      highlight: true,
      colour: "blue",
      numbers: [54, 64, 72],
    },
    {
      id: 64,
      highlight: false,
      colour: "blue",
      numbers: [55, 63, 65, 73],
    },
    {
      id: 65,
      highlight: true,
      colour: "yellow",
      numbers: [56, 64, 66, 74],
    },
    {
      id: 66,
      highlight: false,
      colour: "blue",
      numbers: [57, 65, 67, 75],
    },
    {
      id: 67,
      highlight: false,
      colour: "yellow",
      numbers: [58, 66, 68, 76],
    },
    {
      id: 68,
      highlight: false,
      colour: "blue",
      numbers: [59, 67, 69, 77],
    },
    {
      id: 69,
      highlight: true,
      colour: "yellow",
      numbers: [60, 68, 70, 78],
    },
    {
      id: 70,
      highlight: false,
      colour: "blue",
      numbers: [61, 69, 71, 79],
    },
    {
      id: 71,
      highlight: true,
      colour: "blue",
      numbers: [62, 70, 80],
    },
    {
      id: 72,
      highlight: true,
      colour: "blue",
      numbers: [63, 73],
    },
    {
      id: 73,
      highlight: true,
      colour: "blue",
      numbers: [64, 72, 74],
    },
    {
      id: 74,
      highlight: false,
      colour: "blue",
      numbers: [65, 73, 75],
    },
    {
      id: 75,
      highlight: false,
      colour: "yellow",
      numbers: [66, 74, 76],
    },
    {
      id: 76,
      highlight: false,
      colour: "yellow",
      numbers: [67, 75, 77],
    },
    {
      id: 77,
      highlight: false,
      colour: "yellow",
      numbers: [68, 76, 78],
    },
    {
      id: 78,
      highlight: false,
      colour: "blue",
      numbers: [69, 77, 79],
    },
    {
      id: 79,
      highlight: true,
      colour: "blue",
      numbers: [70, 78, 80],
    },
    {
      id: 80,
      highlight: true,
      colour: "blue",
      numbers: [71, 79],
    },
  ],
];

export default nineLevels;
