const sevenLevels = [
  [
    {
      id: 0,
      highlight: true,
      colour: "yellow",
      numbers: [1, 7],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 8],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 9],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 10],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 11],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [4, 6, 12],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [5, 13],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [0, 8, 14],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [1, 7, 9, 15],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [2, 8, 10, 16],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [3, 9, 11, 17],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [4, 10, 12, 18],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [5, 11, 13, 19],
    },
    {
      id: 13,
      highlight: true,
      colour: "yellow",
      numbers: [6, 12, 20],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [7, 15, 21],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [8, 14, 16, 22],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [9, 15, 17, 23],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [10, 16, 18, 24],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [11, 17, 19, 25],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [12, 18, 20, 26],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [13, 19, 27],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [14, 22, 28],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [15, 21, 23, 29],
    },
    {
      id: 23,
      highlight: true,
      colour: "blue",
      numbers: [16, 22, 24, 30],
    },
    {
      id: 24,
      highlight: false,
      colour: "blue",
      numbers: [17, 23, 25, 31],
    },
    {
      id: 25,
      highlight: true,
      colour: "blue",
      numbers: [18, 24, 26, 32],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [19, 25, 27, 33],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [20, 26, 34],
    },
    {
      id: 28,
      highlight: false,
      colour: "yellow",
      numbers: [21, 29, 35],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [22, 28, 30, 36],
    },
    {
      id: 30,
      highlight: true,
      colour: "blue",
      numbers: [23, 29, 31, 37],
    },
    {
      id: 31,
      highlight: true,
      colour: "blue",
      numbers: [24, 30, 32, 38],
    },
    {
      id: 32,
      highlight: true,
      colour: "blue",
      numbers: [25, 31, 33, 39],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [26, 32, 34, 40],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [27, 33, 41],
    },
    {
      id: 35,
      highlight: true,
      colour: "yellow",
      numbers: [28, 36, 42],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [29, 35, 37, 43],
    },
    {
      id: 37,
      highlight: true,
      colour: "blue",
      numbers: [30, 36, 38, 44],
    },
    {
      id: 38,
      highlight: true,
      colour: "blue",
      numbers: [31, 37, 39, 45],
    },
    {
      id: 39,
      highlight: true,
      colour: "blue",
      numbers: [32, 38, 40, 46],
    },
    {
      id: 40,
      highlight: false,
      colour: "yellow",
      numbers: [33, 39, 41, 47],
    },
    {
      id: 41,
      highlight: true,
      colour: "yellow",
      numbers: [34, 40, 48],
    },
    {
      id: 42,
      highlight: true,
      colour: "yellow",
      numbers: [35, 43],
    },
    {
      id: 43,
      highlight: true,
      colour: "yellow",
      numbers: [36, 42, 44],
    },
    {
      id: 44,
      highlight: true,
      colour: "blue",
      numbers: [37, 43, 45],
    },
    {
      id: 45,
      highlight: false,
      colour: "blue",
      numbers: [38, 44, 46],
    },
    {
      id: 46,
      highlight: true,
      colour: "blue",
      numbers: [39, 45, 47],
    },
    {
      id: 47,
      highlight: true,
      colour: "yellow",
      numbers: [40, 46, 48],
    },
    {
      id: 48,
      highlight: true,
      colour: "yellow",
      numbers: [41, 47],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 7],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 8],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 9],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 10],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [3, 5, 11],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 12],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [5, 13],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [0, 8, 14],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [1, 7, 9, 15],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [2, 8, 10, 16],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [3, 9, 11, 17],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [4, 10, 12, 18],
    },
    {
      id: 12,
      highlight: true,
      colour: "yellow",
      numbers: [5, 11, 13, 19],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [6, 12, 20],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [7, 15, 21],
    },
    {
      id: 15,
      highlight: true,
      colour: "blue",
      numbers: [8, 14, 16, 22],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [9, 15, 17, 23],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [10, 16, 18, 24],
    },
    {
      id: 18,
      highlight: true,
      colour: "blue",
      numbers: [11, 17, 19, 25],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [12, 18, 20, 26],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [13, 19, 27],
    },
    {
      id: 21,
      highlight: true,
      colour: "blue",
      numbers: [14, 22, 28],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [15, 21, 23, 29],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [16, 22, 24, 30],
    },
    {
      id: 24,
      highlight: true,
      colour: "blue",
      numbers: [17, 23, 25, 31],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [18, 24, 26, 32],
    },
    {
      id: 26,
      highlight: true,
      colour: "yellow",
      numbers: [19, 25, 27, 33],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [20, 26, 34],
    },
    {
      id: 28,
      highlight: false,
      colour: "yellow",
      numbers: [21, 29, 35],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [22, 28, 30, 36],
    },
    {
      id: 30,
      highlight: false,
      colour: "blue",
      numbers: [23, 29, 31, 37],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [24, 30, 32, 38],
    },
    {
      id: 32,
      highlight: false,
      colour: "blue",
      numbers: [25, 31, 33, 39],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [26, 32, 34, 40],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [27, 33, 41],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [28, 36, 42],
    },
    {
      id: 36,
      highlight: true,
      colour: "blue",
      numbers: [29, 35, 37, 43],
    },
    {
      id: 37,
      highlight: false,
      colour: "blue",
      numbers: [30, 36, 38, 44],
    },
    {
      id: 38,
      highlight: false,
      colour: "blue",
      numbers: [31, 37, 39, 45],
    },
    {
      id: 39,
      highlight: false,
      colour: "blue",
      numbers: [32, 38, 40, 46],
    },
    {
      id: 40,
      highlight: true,
      colour: "blue",
      numbers: [33, 39, 41, 47],
    },
    {
      id: 41,
      highlight: false,
      colour: "yellow",
      numbers: [34, 40, 48],
    },
    {
      id: 42,
      highlight: false,
      colour: "yellow",
      numbers: [35, 43],
    },
    {
      id: 43,
      highlight: true,
      colour: "blue",
      numbers: [36, 42, 44],
    },
    {
      id: 44,
      highlight: false,
      colour: "blue",
      numbers: [37, 43, 45],
    },
    {
      id: 45,
      highlight: false,
      colour: "blue",
      numbers: [38, 44, 46],
    },
    {
      id: 46,
      highlight: false,
      colour: "blue",
      numbers: [39, 45, 47],
    },
    {
      id: 47,
      highlight: true,
      colour: "blue",
      numbers: [40, 46, 48],
    },
    {
      id: 48,
      highlight: false,
      colour: "yellow",
      numbers: [41, 47],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 7],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 8],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 9],
    },
    {
      id: 3,
      highlight: true,
      colour: "yellow",
      numbers: [2, 4, 10],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [3, 5, 11],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 12],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [5, 13],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [0, 8, 14],
    },
    {
      id: 8,
      highlight: true,
      colour: "blue",
      numbers: [1, 7, 9, 15],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [2, 8, 10, 16],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [3, 9, 11, 17],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [4, 10, 12, 18],
    },
    {
      id: 12,
      highlight: true,
      colour: "blue",
      numbers: [5, 11, 13, 19],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [6, 12, 20],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [7, 15, 21],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [8, 14, 16, 22],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [9, 15, 17, 23],
    },
    {
      id: 17,
      highlight: false,
      colour: "yellow",
      numbers: [10, 16, 18, 24],
    },
    {
      id: 18,
      highlight: true,
      colour: "blue",
      numbers: [11, 17, 19, 25],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [12, 18, 20, 26],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [13, 19, 27],
    },
    {
      id: 21,
      highlight: true,
      colour: "yellow",
      numbers: [14, 22, 28],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [15, 21, 23, 29],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [16, 22, 24, 30],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [17, 23, 25, 31],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [18, 24, 26, 32],
    },
    {
      id: 26,
      highlight: true,
      colour: "yellow",
      numbers: [19, 25, 27, 33],
    },
    {
      id: 27,
      highlight: true,
      colour: "yellow",
      numbers: [20, 26, 34],
    },
    {
      id: 28,
      highlight: true,
      colour: "blue",
      numbers: [21, 29, 35],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [22, 28, 30, 36],
    },
    {
      id: 30,
      highlight: true,
      colour: "blue",
      numbers: [23, 29, 31, 37],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [24, 30, 32, 38],
    },
    {
      id: 32,
      highlight: true,
      colour: "blue",
      numbers: [25, 31, 33, 39],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [26, 32, 34, 40],
    },
    {
      id: 34,
      highlight: true,
      colour: "blue",
      numbers: [27, 33, 41],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [28, 36, 42],
    },
    {
      id: 36,
      highlight: true,
      colour: "blue",
      numbers: [29, 35, 37, 43],
    },
    {
      id: 37,
      highlight: false,
      colour: "yellow",
      numbers: [30, 36, 38, 44],
    },
    {
      id: 38,
      highlight: true,
      colour: "yellow",
      numbers: [31, 37, 39, 45],
    },
    {
      id: 39,
      highlight: false,
      colour: "yellow",
      numbers: [32, 38, 40, 46],
    },
    {
      id: 40,
      highlight: true,
      colour: "blue",
      numbers: [33, 39, 41, 47],
    },
    {
      id: 41,
      highlight: false,
      colour: "yellow",
      numbers: [34, 40, 48],
    },
    {
      id: 42,
      highlight: false,
      colour: "yellow",
      numbers: [35, 43],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [36, 42, 44],
    },
    {
      id: 44,
      highlight: true,
      colour: "yellow",
      numbers: [37, 43, 45],
    },
    {
      id: 45,
      highlight: true,
      colour: "yellow",
      numbers: [38, 44, 46],
    },
    {
      id: 46,
      highlight: true,
      colour: "yellow",
      numbers: [39, 45, 47],
    },
    {
      id: 47,
      highlight: false,
      colour: "yellow",
      numbers: [40, 46, 48],
    },
    {
      id: 48,
      highlight: false,
      colour: "yellow",
      numbers: [41, 47],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 7],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 8],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 9],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 10],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 5, 11],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 6, 12],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [5, 13],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [0, 8, 14],
    },
    {
      id: 8,
      highlight: false,
      colour: "blue",
      numbers: [1, 7, 9, 15],
    },
    {
      id: 9,
      highlight: false,
      colour: "blue",
      numbers: [2, 8, 10, 16],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [3, 9, 11, 17],
    },
    {
      id: 11,
      highlight: false,
      colour: "blue",
      numbers: [4, 10, 12, 18],
    },
    {
      id: 12,
      highlight: false,
      colour: "blue",
      numbers: [5, 11, 13, 19],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [6, 12, 20],
    },
    {
      id: 14,
      highlight: true,
      colour: "yellow",
      numbers: [7, 15, 21],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [8, 14, 16, 22],
    },
    {
      id: 16,
      highlight: false,
      colour: "blue",
      numbers: [9, 15, 17, 23],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [10, 16, 18, 24],
    },
    {
      id: 18,
      highlight: false,
      colour: "blue",
      numbers: [11, 17, 19, 25],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [12, 18, 20, 26],
    },
    {
      id: 20,
      highlight: true,
      colour: "yellow",
      numbers: [13, 19, 27],
    },
    {
      id: 21,
      highlight: true,
      colour: "yellow",
      numbers: [14, 22, 28],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [15, 21, 23, 29],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [16, 22, 24, 30],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [17, 23, 25, 31],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [18, 24, 26, 32],
    },
    {
      id: 26,
      highlight: true,
      colour: "yellow",
      numbers: [19, 25, 27, 33],
    },
    {
      id: 27,
      highlight: true,
      colour: "yellow",
      numbers: [20, 26, 34],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [21, 29, 35],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [22, 28, 30, 36],
    },
    {
      id: 30,
      highlight: false,
      colour: "blue",
      numbers: [23, 29, 31, 37],
    },
    {
      id: 31,
      highlight: true,
      colour: "blue",
      numbers: [24, 30, 32, 38],
    },
    {
      id: 32,
      highlight: false,
      colour: "blue",
      numbers: [25, 31, 33, 39],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [26, 32, 34, 40],
    },
    {
      id: 34,
      highlight: true,
      colour: "yellow",
      numbers: [27, 33, 41],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [28, 36, 42],
    },
    {
      id: 36,
      highlight: false,
      colour: "blue",
      numbers: [29, 35, 37, 43],
    },
    {
      id: 37,
      highlight: false,
      colour: "blue",
      numbers: [30, 36, 38, 44],
    },
    {
      id: 38,
      highlight: true,
      colour: "blue",
      numbers: [31, 37, 39, 45],
    },
    {
      id: 39,
      highlight: false,
      colour: "blue",
      numbers: [32, 38, 40, 46],
    },
    {
      id: 40,
      highlight: false,
      colour: "blue",
      numbers: [33, 39, 41, 47],
    },
    {
      id: 41,
      highlight: false,
      colour: "yellow",
      numbers: [34, 40, 48],
    },
    {
      id: 42,
      highlight: false,
      colour: "yellow",
      numbers: [35, 43],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [36, 42, 44],
    },
    {
      id: 44,
      highlight: true,
      colour: "blue",
      numbers: [37, 43, 45],
    },
    {
      id: 45,
      highlight: true,
      colour: "blue",
      numbers: [38, 44, 46],
    },
    {
      id: 46,
      highlight: true,
      colour: "blue",
      numbers: [39, 45, 47],
    },
    {
      id: 47,
      highlight: false,
      colour: "yellow",
      numbers: [40, 46, 48],
    },
    {
      id: 48,
      highlight: false,
      colour: "yellow",
      numbers: [41, 47],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 7],
    },
    {
      id: 1,
      highlight: false,
      colour: "blue",
      numbers: [0, 2, 8],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 9],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 10],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 5, 11],
    },
    {
      id: 5,
      highlight: false,
      colour: "blue",
      numbers: [4, 6, 12],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [5, 13],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [0, 8, 14],
    },
    {
      id: 8,
      highlight: false,
      colour: "blue",
      numbers: [1, 7, 9, 15],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [2, 8, 10, 16],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [3, 9, 11, 17],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [4, 10, 12, 18],
    },
    {
      id: 12,
      highlight: false,
      colour: "blue",
      numbers: [5, 11, 13, 19],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [6, 12, 20],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [7, 15, 21],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [8, 14, 16, 22],
    },
    {
      id: 16,
      highlight: true,
      colour: "yellow",
      numbers: [9, 15, 17, 23],
    },
    {
      id: 17,
      highlight: false,
      colour: "yellow",
      numbers: [10, 16, 18, 24],
    },
    {
      id: 18,
      highlight: true,
      colour: "yellow",
      numbers: [11, 17, 19, 25],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [12, 18, 20, 26],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [13, 19, 27],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [14, 22, 28],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [15, 21, 23, 29],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [16, 22, 24, 30],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [17, 23, 25, 31],
    },
    {
      id: 25,
      highlight: false,
      colour: "yellow",
      numbers: [18, 24, 26, 32],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [19, 25, 27, 33],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [20, 26, 34],
    },
    {
      id: 28,
      highlight: false,
      colour: "yellow",
      numbers: [21, 29, 35],
    },
    {
      id: 29,
      highlight: false,
      colour: "blue",
      numbers: [22, 28, 30, 36],
    },
    {
      id: 30,
      highlight: true,
      colour: "blue",
      numbers: [23, 29, 31, 37],
    },
    {
      id: 31,
      highlight: false,
      colour: "blue",
      numbers: [24, 30, 32, 38],
    },
    {
      id: 32,
      highlight: true,
      colour: "blue",
      numbers: [25, 31, 33, 39],
    },
    {
      id: 33,
      highlight: false,
      colour: "blue",
      numbers: [26, 32, 34, 40],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [27, 33, 41],
    },
    {
      id: 35,
      highlight: true,
      colour: "yellow",
      numbers: [28, 36, 42],
    },
    {
      id: 36,
      highlight: false,
      colour: "yellow",
      numbers: [29, 35, 37, 43],
    },
    {
      id: 37,
      highlight: false,
      colour: "blue",
      numbers: [30, 36, 38, 44],
    },
    {
      id: 38,
      highlight: false,
      colour: "yellow",
      numbers: [31, 37, 39, 45],
    },
    {
      id: 39,
      highlight: false,
      colour: "blue",
      numbers: [32, 38, 40, 46],
    },
    {
      id: 40,
      highlight: false,
      colour: "yellow",
      numbers: [33, 39, 41, 47],
    },
    {
      id: 41,
      highlight: true,
      colour: "yellow",
      numbers: [34, 40, 48],
    },
    {
      id: 42,
      highlight: true,
      colour: "yellow",
      numbers: [35, 43],
    },
    {
      id: 43,
      highlight: false,
      colour: "yellow",
      numbers: [36, 42, 44],
    },
    {
      id: 44,
      highlight: true,
      colour: "yellow",
      numbers: [37, 43, 45],
    },
    {
      id: 45,
      highlight: false,
      colour: "yellow",
      numbers: [38, 44, 46],
    },
    {
      id: 46,
      highlight: true,
      colour: "yellow",
      numbers: [39, 45, 47],
    },
    {
      id: 47,
      highlight: false,
      colour: "yellow",
      numbers: [40, 46, 48],
    },
    {
      id: 48,
      highlight: true,
      colour: "yellow",
      numbers: [41, 47],
    },
  ],
];

export default sevenLevels;
