const sixLevels = [
  [
    {
      id: 0,
      highlight: true,
      colour: "yellow",
      numbers: [1, 6],
    },
    {
      id: 1,
      highlight: false,
      colour: "yellow",
      numbers: [0, 2, 7],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 8],
    },
    {
      id: 3,
      highlight: true,
      colour: "yellow",
      numbers: [2, 4, 9],
    },
    {
      id: 4,
      highlight: false,
      colour: "yellow",
      numbers: [3, 5, 10],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [4, 11],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [0, 7, 12],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [1, 6, 8, 13],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [2, 7, 9, 14],
    },
    {
      id: 9,
      highlight: true,
      colour: "yellow",
      numbers: [3, 8, 10, 15],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [4, 9, 11, 16],
    },
    {
      id: 11,
      highlight: true,
      colour: "blue",
      numbers: [5, 10, 17],
    },
    {
      id: 12,
      highlight: false,
      colour: "blue",
      numbers: [6, 13, 18],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [7, 12, 14, 19],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [8, 13, 15, 20],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [9, 14, 16, 21],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [10, 15, 17, 22],
    },
    {
      id: 17,
      highlight: false,
      colour: "blue",
      numbers: [11, 16, 23],
    },
    {
      id: 18,
      highlight: false,
      colour: "blue",
      numbers: [12, 19, 24],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [13, 18, 20, 25],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [14, 19, 21, 26],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [15, 20, 22, 27],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [16, 21, 23, 28],
    },
    {
      id: 23,
      highlight: false,
      colour: "blue",
      numbers: [17, 22, 29],
    },
    {
      id: 24,
      highlight: true,
      colour: "blue",
      numbers: [18, 25, 30],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [19, 24, 26, 31],
    },
    {
      id: 26,
      highlight: true,
      colour: "yellow",
      numbers: [20, 25, 27, 32],
    },
    {
      id: 27,
      highlight: true,
      colour: "yellow",
      numbers: [21, 26, 28, 33],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [22, 27, 29, 34],
    },
    {
      id: 29,
      highlight: true,
      colour: "blue",
      numbers: [23, 28, 35],
    },
    {
      id: 30,
      highlight: true,
      colour: "yellow",
      numbers: [24, 31],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [25, 30, 32],
    },
    {
      id: 32,
      highlight: true,
      colour: "yellow",
      numbers: [26, 31, 33],
    },
    {
      id: 33,
      highlight: true,
      colour: "yellow",
      numbers: [27, 32, 34],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [28, 33, 35],
    },
    {
      id: 35,
      highlight: true,
      colour: "yellow",
      numbers: [29, 34],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 6],
    },
    {
      id: 1,
      highlight: true,
      colour: "blue",
      numbers: [0, 2, 7],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 8],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 9],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 5, 10],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 11],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [0, 7, 12],
    },
    {
      id: 7,
      highlight: false,
      colour: "yellow",
      numbers: [1, 6, 8, 13],
    },
    {
      id: 8,
      highlight: true,
      colour: "blue",
      numbers: [2, 7, 9, 14],
    },
    {
      id: 9,
      highlight: true,
      colour: "blue",
      numbers: [3, 8, 10, 15],
    },
    {
      id: 10,
      highlight: false,
      colour: "yellow",
      numbers: [4, 9, 11, 16],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [5, 10, 17],
    },
    {
      id: 12,
      highlight: true,
      colour: "yellow",
      numbers: [6, 13, 18],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [7, 12, 14, 19],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [8, 13, 15, 20],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [9, 14, 16, 21],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [10, 15, 17, 22],
    },
    {
      id: 17,
      highlight: true,
      colour: "yellow",
      numbers: [11, 16, 23],
    },
    {
      id: 18,
      highlight: true,
      colour: "yellow",
      numbers: [12, 19, 24],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [13, 18, 20, 25],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [14, 19, 21, 26],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [15, 20, 22, 27],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [16, 21, 23, 28],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [17, 22, 29],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [18, 25, 30],
    },
    {
      id: 25,
      highlight: false,
      colour: "yellow",
      numbers: [19, 24, 26, 31],
    },
    {
      id: 26,
      highlight: true,
      colour: "blue",
      numbers: [20, 25, 27, 32],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [21, 26, 28, 33],
    },
    {
      id: 28,
      highlight: false,
      colour: "yellow",
      numbers: [22, 27, 29, 34],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [23, 28, 35],
    },
    {
      id: 30,
      highlight: false,
      colour: "yellow",
      numbers: [24, 31],
    },
    {
      id: 31,
      highlight: true,
      colour: "blue",
      numbers: [25, 30, 32],
    },
    {
      id: 32,
      highlight: true,
      colour: "blue",
      numbers: [26, 31, 33],
    },
    {
      id: 33,
      highlight: true,
      colour: "blue",
      numbers: [27, 32, 34],
    },
    {
      id: 34,
      highlight: true,
      colour: "blue",
      numbers: [28, 33, 35],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [29, 34],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "yellow",
      numbers: [1, 6],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 7],
    },
    {
      id: 2,
      highlight: true,
      colour: "yellow",
      numbers: [1, 3, 8],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 9],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 5, 10],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [4, 11],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [0, 7, 12],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [1, 6, 8, 13],
    },
    {
      id: 8,
      highlight: true,
      colour: "yellow",
      numbers: [2, 7, 9, 14],
    },
    {
      id: 9,
      highlight: true,
      colour: "blue",
      numbers: [3, 8, 10, 15],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [4, 9, 11, 16],
    },
    {
      id: 11,
      highlight: true,
      colour: "blue",
      numbers: [5, 10, 17],
    },
    {
      id: 12,
      highlight: true,
      colour: "yellow",
      numbers: [6, 13, 18],
    },
    {
      id: 13,
      highlight: true,
      colour: "yellow",
      numbers: [7, 12, 14, 19],
    },
    {
      id: 14,
      highlight: false,
      colour: "yellow",
      numbers: [8, 13, 15, 20],
    },
    {
      id: 15,
      highlight: false,
      colour: "yellow",
      numbers: [9, 14, 16, 21],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [10, 15, 17, 22],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [11, 16, 23],
    },
    {
      id: 18,
      highlight: true,
      colour: "blue",
      numbers: [12, 19, 24],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [13, 18, 20, 25],
    },
    {
      id: 20,
      highlight: false,
      colour: "yellow",
      numbers: [14, 19, 21, 26],
    },
    {
      id: 21,
      highlight: false,
      colour: "yellow",
      numbers: [15, 20, 22, 27],
    },
    {
      id: 22,
      highlight: true,
      colour: "yellow",
      numbers: [16, 21, 23, 28],
    },
    {
      id: 23,
      highlight: true,
      colour: "yellow",
      numbers: [17, 22, 29],
    },
    {
      id: 24,
      highlight: true,
      colour: "blue",
      numbers: [18, 25, 30],
    },
    {
      id: 25,
      highlight: true,
      colour: "blue",
      numbers: [19, 24, 26, 31],
    },
    {
      id: 26,
      highlight: true,
      colour: "blue",
      numbers: [20, 25, 27, 32],
    },
    {
      id: 27,
      highlight: true,
      colour: "yellow",
      numbers: [21, 26, 28, 33],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [22, 27, 29, 34],
    },
    {
      id: 29,
      highlight: true,
      colour: "yellow",
      numbers: [23, 28, 35],
    },
    {
      id: 30,
      highlight: true,
      colour: "blue",
      numbers: [24, 31],
    },
    {
      id: 31,
      highlight: true,
      colour: "blue",
      numbers: [25, 30, 32],
    },
    {
      id: 32,
      highlight: true,
      colour: "blue",
      numbers: [26, 31, 33],
    },
    {
      id: 33,
      highlight: true,
      colour: "yellow",
      numbers: [27, 32, 34],
    },
    {
      id: 34,
      highlight: true,
      colour: "yellow",
      numbers: [28, 33, 35],
    },
    {
      id: 35,
      highlight: true,
      colour: "yellow",
      numbers: [29, 34],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 6],
    },
    {
      id: 1,
      highlight: true,
      colour: "blue",
      numbers: [0, 2, 7],
    },
    {
      id: 2,
      highlight: true,
      colour: "blue",
      numbers: [1, 3, 8],
    },
    {
      id: 3,
      highlight: true,
      colour: "blue",
      numbers: [2, 4, 9],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 5, 10],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 11],
    },
    {
      id: 6,
      highlight: true,
      colour: "blue",
      numbers: [0, 7, 12],
    },
    {
      id: 7,
      highlight: true,
      colour: "blue",
      numbers: [1, 6, 8, 13],
    },
    {
      id: 8,
      highlight: false,
      colour: "blue",
      numbers: [2, 7, 9, 14],
    },
    {
      id: 9,
      highlight: false,
      colour: "blue",
      numbers: [3, 8, 10, 15],
    },
    {
      id: 10,
      highlight: true,
      colour: "blue",
      numbers: [4, 9, 11, 16],
    },
    {
      id: 11,
      highlight: true,
      colour: "blue",
      numbers: [5, 10, 17],
    },
    {
      id: 12,
      highlight: true,
      colour: "blue",
      numbers: [6, 13, 18],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [7, 12, 14, 19],
    },
    {
      id: 14,
      highlight: false,
      colour: "blue",
      numbers: [8, 13, 15, 20],
    },
    {
      id: 15,
      highlight: false,
      colour: "blue",
      numbers: [9, 14, 16, 21],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [10, 15, 17, 22],
    },
    {
      id: 17,
      highlight: true,
      colour: "blue",
      numbers: [11, 16, 23],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [12, 19, 24],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [13, 18, 20, 25],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [14, 19, 21, 26],
    },
    {
      id: 21,
      highlight: true,
      colour: "blue",
      numbers: [15, 20, 22, 27],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [16, 21, 23, 28],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [17, 22, 29],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [18, 25, 30],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [19, 24, 26, 31],
    },
    {
      id: 26,
      highlight: true,
      colour: "yellow",
      numbers: [20, 25, 27, 32],
    },
    {
      id: 27,
      highlight: true,
      colour: "yellow",
      numbers: [21, 26, 28, 33],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [22, 27, 29, 34],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [23, 28, 35],
    },
    {
      id: 30,
      highlight: true,
      colour: "yellow",
      numbers: [24, 31],
    },
    {
      id: 31,
      highlight: false,
      colour: "yellow",
      numbers: [25, 30, 32],
    },
    {
      id: 32,
      highlight: true,
      colour: "yellow",
      numbers: [26, 31, 33],
    },
    {
      id: 33,
      highlight: true,
      colour: "yellow",
      numbers: [27, 32, 34],
    },
    {
      id: 34,
      highlight: false,
      colour: "yellow",
      numbers: [28, 33, 35],
    },
    {
      id: 35,
      highlight: true,
      colour: "yellow",
      numbers: [29, 34],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "blue",
      numbers: [1, 6],
    },
    {
      id: 1,
      highlight: true,
      colour: "blue",
      numbers: [0, 2, 7],
    },
    {
      id: 2,
      highlight: false,
      colour: "blue",
      numbers: [1, 3, 8],
    },
    {
      id: 3,
      highlight: false,
      colour: "blue",
      numbers: [2, 4, 9],
    },
    {
      id: 4,
      highlight: true,
      colour: "blue",
      numbers: [3, 5, 10],
    },
    {
      id: 5,
      highlight: true,
      colour: "blue",
      numbers: [4, 11],
    },
    {
      id: 6,
      highlight: false,
      colour: "yellow",
      numbers: [0, 7, 12],
    },
    {
      id: 7,
      highlight: false,
      colour: "blue",
      numbers: [1, 6, 8, 13],
    },
    {
      id: 8,
      highlight: false,
      colour: "blue",
      numbers: [2, 7, 9, 14],
    },
    {
      id: 9,
      highlight: false,
      colour: "blue",
      numbers: [3, 8, 10, 15],
    },
    {
      id: 10,
      highlight: false,
      colour: "blue",
      numbers: [4, 9, 11, 16],
    },
    {
      id: 11,
      highlight: false,
      colour: "yellow",
      numbers: [5, 10, 17],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [6, 13, 18],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [7, 12, 14, 19],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [8, 13, 15, 20],
    },
    {
      id: 15,
      highlight: true,
      colour: "blue",
      numbers: [9, 14, 16, 21],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [10, 15, 17, 22],
    },
    {
      id: 17,
      highlight: false,
      colour: "yellow",
      numbers: [11, 16, 23],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [12, 19, 24],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [13, 18, 20, 25],
    },
    {
      id: 20,
      highlight: true,
      colour: "yellow",
      numbers: [14, 19, 21, 26],
    },
    {
      id: 21,
      highlight: true,
      colour: "yellow",
      numbers: [15, 20, 22, 27],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [16, 21, 23, 28],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [17, 22, 29],
    },
    {
      id: 24,
      highlight: false,
      colour: "yellow",
      numbers: [18, 25, 30],
    },
    {
      id: 25,
      highlight: false,
      colour: "yellow",
      numbers: [19, 24, 26, 31],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [20, 25, 27, 32],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [21, 26, 28, 33],
    },
    {
      id: 28,
      highlight: false,
      colour: "yellow",
      numbers: [22, 27, 29, 34],
    },
    {
      id: 29,
      highlight: false,
      colour: "yellow",
      numbers: [23, 28, 35],
    },
    {
      id: 30,
      highlight: true,
      colour: "yellow",
      numbers: [24, 31],
    },
    {
      id: 31,
      highlight: true,
      colour: "yellow",
      numbers: [25, 30, 32],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [26, 31, 33],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [27, 32, 34],
    },
    {
      id: 34,
      highlight: true,
      colour: "yellow",
      numbers: [28, 33, 35],
    },
    {
      id: 35,
      highlight: true,
      colour: "yellow",
      numbers: [29, 34],
    },
  ],
  [
    {
      id: 0,
      highlight: false,
      colour: "yellow",
      numbers: [1, 6],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 7],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 8],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 9],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [3, 5, 10],
    },
    {
      id: 5,
      highlight: false,
      colour: "yellow",
      numbers: [4, 11],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [0, 7, 12],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [1, 6, 8, 13],
    },
    {
      id: 8,
      highlight: false,
      colour: "yellow",
      numbers: [2, 7, 9, 14],
    },
    {
      id: 9,
      highlight: false,
      colour: "yellow",
      numbers: [3, 8, 10, 15],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [4, 9, 11, 16],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [5, 10, 17],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [6, 13, 18],
    },
    {
      id: 13,
      highlight: false,
      colour: "yellow",
      numbers: [7, 12, 14, 19],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [8, 13, 15, 20],
    },
    {
      id: 15,
      highlight: true,
      colour: "blue",
      numbers: [9, 14, 16, 21],
    },
    {
      id: 16,
      highlight: false,
      colour: "yellow",
      numbers: [10, 15, 17, 22],
    },
    {
      id: 17,
      highlight: false,
      colour: "yellow",
      numbers: [11, 16, 23],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [12, 19, 24],
    },
    {
      id: 19,
      highlight: false,
      colour: "yellow",
      numbers: [13, 18, 20, 25],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [14, 19, 21, 26],
    },
    {
      id: 21,
      highlight: true,
      colour: "blue",
      numbers: [15, 20, 22, 27],
    },
    {
      id: 22,
      highlight: false,
      colour: "yellow",
      numbers: [16, 21, 23, 28],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [17, 22, 29],
    },
    {
      id: 24,
      highlight: true,
      colour: "yellow",
      numbers: [18, 25, 30],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [19, 24, 26, 31],
    },
    {
      id: 26,
      highlight: false,
      colour: "yellow",
      numbers: [20, 25, 27, 32],
    },
    {
      id: 27,
      highlight: false,
      colour: "yellow",
      numbers: [21, 26, 28, 33],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [22, 27, 29, 34],
    },
    {
      id: 29,
      highlight: true,
      colour: "yellow",
      numbers: [23, 28, 35],
    },
    {
      id: 30,
      highlight: false,
      colour: "yellow",
      numbers: [24, 31],
    },
    {
      id: 31,
      highlight: true,
      colour: "yellow",
      numbers: [25, 30, 32],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [26, 31, 33],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [27, 32, 34],
    },
    {
      id: 34,
      highlight: true,
      colour: "yellow",
      numbers: [28, 33, 35],
    },
    {
      id: 35,
      highlight: false,
      colour: "yellow",
      numbers: [29, 34],
    },
  ],
  [
    {
      id: 0,
      highlight: true,
      colour: "yellow",
      numbers: [1, 6],
    },
    {
      id: 1,
      highlight: true,
      colour: "yellow",
      numbers: [0, 2, 7],
    },
    {
      id: 2,
      highlight: false,
      colour: "yellow",
      numbers: [1, 3, 8],
    },
    {
      id: 3,
      highlight: false,
      colour: "yellow",
      numbers: [2, 4, 9],
    },
    {
      id: 4,
      highlight: true,
      colour: "yellow",
      numbers: [3, 5, 10],
    },
    {
      id: 5,
      highlight: true,
      colour: "yellow",
      numbers: [4, 11],
    },
    {
      id: 6,
      highlight: true,
      colour: "yellow",
      numbers: [0, 7, 12],
    },
    {
      id: 7,
      highlight: true,
      colour: "yellow",
      numbers: [1, 6, 8, 13],
    },
    {
      id: 8,
      highlight: true,
      colour: "blue",
      numbers: [2, 7, 9, 14],
    },
    {
      id: 9,
      highlight: true,
      colour: "blue",
      numbers: [3, 8, 10, 15],
    },
    {
      id: 10,
      highlight: true,
      colour: "yellow",
      numbers: [4, 9, 11, 16],
    },
    {
      id: 11,
      highlight: true,
      colour: "yellow",
      numbers: [5, 10, 17],
    },
    {
      id: 12,
      highlight: false,
      colour: "yellow",
      numbers: [6, 13, 18],
    },
    {
      id: 13,
      highlight: true,
      colour: "blue",
      numbers: [7, 12, 14, 19],
    },
    {
      id: 14,
      highlight: true,
      colour: "blue",
      numbers: [8, 13, 15, 20],
    },
    {
      id: 15,
      highlight: true,
      colour: "blue",
      numbers: [9, 14, 16, 21],
    },
    {
      id: 16,
      highlight: true,
      colour: "blue",
      numbers: [10, 15, 17, 22],
    },
    {
      id: 17,
      highlight: false,
      colour: "yellow",
      numbers: [11, 16, 23],
    },
    {
      id: 18,
      highlight: false,
      colour: "yellow",
      numbers: [12, 19, 24],
    },
    {
      id: 19,
      highlight: true,
      colour: "blue",
      numbers: [13, 18, 20, 25],
    },
    {
      id: 20,
      highlight: true,
      colour: "blue",
      numbers: [14, 19, 21, 26],
    },
    {
      id: 21,
      highlight: true,
      colour: "blue",
      numbers: [15, 20, 22, 27],
    },
    {
      id: 22,
      highlight: true,
      colour: "blue",
      numbers: [16, 21, 23, 28],
    },
    {
      id: 23,
      highlight: false,
      colour: "yellow",
      numbers: [17, 22, 29],
    },
    {
      id: 24,
      highlight: true,
      colour: "yellow",
      numbers: [18, 25, 30],
    },
    {
      id: 25,
      highlight: true,
      colour: "yellow",
      numbers: [19, 24, 26, 31],
    },
    {
      id: 26,
      highlight: true,
      colour: "blue",
      numbers: [20, 25, 27, 32],
    },
    {
      id: 27,
      highlight: true,
      colour: "blue",
      numbers: [21, 26, 28, 33],
    },
    {
      id: 28,
      highlight: true,
      colour: "yellow",
      numbers: [22, 27, 29, 34],
    },
    {
      id: 29,
      highlight: true,
      colour: "yellow",
      numbers: [23, 28, 35],
    },
    {
      id: 30,
      highlight: true,
      colour: "yellow",
      numbers: [24, 31],
    },
    {
      id: 31,
      highlight: true,
      colour: "yellow",
      numbers: [25, 30, 32],
    },
    {
      id: 32,
      highlight: false,
      colour: "yellow",
      numbers: [26, 31, 33],
    },
    {
      id: 33,
      highlight: false,
      colour: "yellow",
      numbers: [27, 32, 34],
    },
    {
      id: 34,
      highlight: true,
      colour: "yellow",
      numbers: [28, 33, 35],
    },
    {
      id: 35,
      highlight: true,
      colour: "yellow",
      numbers: [29, 34],
    },
  ],
];

export default sixLevels;
